### ISSUE TITLE
just Question : what is the grafana version number included on hte add-on?

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-grafana#1]
Very nice to see the grafana add-on included on your repertoire ! , thankyou

would like to know what is the version number , in order to check compatibility with my actual  grafana dashboards, and influx db version .

**Comment by frenck** [comment]
Hi @gnkarn,

The current version is 5.1.3 (latest stable version).

Any future version updated will be announced via the changelogs, forum topic announcements and in the release notes.

This is the location of the version definition in the code:
https://github.com/hassio-addons/addon-grafana/blob/4ba71f60e0f42f2f581e284daeca2ccee8c20d78/grafana/Dockerfile#L9
