### ISSUE TITLE
Allow access to non-administrator users?

### ISSUE THREAD

**Issue by deviantintegral** [hassio-addons/addon-grafana#100]
# Problem/Motivation

The Grafana addon in the sidebar does not show up for non-administrator users. Is this by design? On the one hand, I see that the automatic admin login could be a security issue. However, I'd expect that non-admin HA users would be able to access Grafana, but in an anonymous state to that app.

## Expected behavior

I expect some sort of configuration and docs for setting up anonymous access. While I could expose the Grafana port, that doesn't help for remote access through Home Assistant Cloud.

## Actual behavior

Only admins can view Grafana.

## Proposed changes

This may just be a docs issue, or by design, so clarity for that would help determine next steps.

**Comment by frenck** [comment]
> The Grafana addon in the sidebar does not show up for non-administrator users. Is this by design?

Nope, a limitation from the Home Assistant platform at this point. There is no control or choice from an add-on perspective.

So this isn't by design, nor an add-on issue or limitation.
