### ISSUE TITLE
Default Admin Password Can't Be Changed

### ISSUE THREAD

**Issue by ehbush** [hassio-addons/addon-grafana#106]
# Problem/Motivation

> I may just be being dense, and I apologise if that is the case - but in attempting to change the default user's password, I was greeted with a error message of: 

`You cannot change password when ldap or auth proxy authentication is enabled.`

## Expected behavior

> Expected to be able to change the password for the user in Grafana (in this case, the default admin user's pass) 

## Actual behavior

>`You cannot change password when ldap or auth proxy authentication is enabled.`

## Steps to reproduce

> Brand new install of InfluxDB HASS Addon, followed-up by installing this Grafana add-on. 

## Proposed changes

> Not sure what the error is, but in poking around it appears that auth_proxy is enabled (I assume for the creation of the initial user and/or because of the iframing or the way hass handle's add-ons?).  Additionally, both auth_generic_oauth and auth_gitlab are enabled (though I believe this is unrelated, just making the observation since I'm not entirely certain where the issue may be). 

The documentation here suggests changing the default password of course, but I must be missing something because it cannot be performed out-the-box as far as I can tell.

**Comment by sinclairpaul** [comment]
Unfortunately it is a side effect of how we provide both Ingress and direct access.

The only workaround is to create a new user and delete the original one (while updating the addon config).

I'll do a PR on the docs at some point.
