### ISSUE TITLE
Grafana docker container does not start

### ISSUE THREAD

**Issue by basbroekman** [hassio-addons/addon-grafana#111]
# Problem/Motivation

> Grafana docker container does not start anymore since last update.

Error message is:
400 Client Error for http+docker://localhost/v1.39/containers/0376bf70cf54291964e7ddf072e61212a5b340bd1ca6f233f207d0442674b364/start: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")

## Steps to reproduce

> (How can someone else make/see it happen)
Using version 2021.02.6 of the Supervisor, click 'Start' on the Grafana version 6.1.1 add-on and above error message appears.

![image](https://user-images.githubusercontent.com/72770650/107880503-679c7000-6edf-11eb-82f0-5891b661a3cd.png)

**Comment by frenck** [comment]
Please provide the output of `ha info`, thanks 👍

**Comment by basbroekman** [comment]
arch: amd64
channel: stable
docker: 18.09.8
features: []
hassos: null
homeassistant: 2021.2.3
hostname: null
logging: info
machine: qemux86-64
operating_system: null
state: running
supervisor: 2021.02.9
supported: false
supported_arch:
- amd64
- i386
timezone: Europe/Amsterdam

**Comment by frenck** [comment]
That is a weird reading to get. The first thing to notice, is the empty `operating_system`, which is weird and the Docker version is outdated (doesn't meet the requirements for a Home Assistant Supervised installation).

Please make sure you run a valid Docker version and that your system has the appropriate permissions.

**Comment by basbroekman** [comment]
I was already afraid the os would not be supported. I think I cannot update docker as it is running on Synology DSM. Hassio is installed using this package: https://synocommunity.com/package/hassio. Hopefully not many more packages will stop working with next updates. Keep up the good work and thanks for you time though

**Comment by frenck** [comment]
Running Home Assistant Supervised was never supported, and would highly recommend on not using that. It will cause problems, as we have been warning about for a long time already.
