### ISSUE TITLE
Rerverse proxy for grafana direct access

### ISSUE THREAD

**Issue by vajonam** [hassio-addons/addon-grafana#118]
# Problem/Motivation

I would to get my grafana working though a reverse proxy with direct access.

## Expected behavior

direct access works with

```
location /grafana/ {
    rewrite ^/grafana(/.*)$ $1 break;
    proxy_pass  https://hassio.local:3000/;
}
```

## Actual behavior

it redirects me to https://myrevproxyhost.com/api/hassio_ingress/BVXk-somerandomID-DHrwY9zwosNuVeSs/

## Steps to reproduce

use above nginx settings

## Proposed changes

none. I understand if this technically not feasible because of the how direct access is now implemented  that has some redirects built in.  I see some older issues when this first changes. not sure if anything has changed since then.

**Comment by sinclairpaul** [comment]
In order to serve from a subfolder, you need to change the root_url config in the grafana.ini.  Unfortunately we already set this to support ingress and direct access so it cannot be easily changed.

I would suggest the addon does not meet your use case.
