### ISSUE TITLE
No Dashboards

### ISSUE THREAD

**Issue by jarrodlucia** [hassio-addons/addon-grafana#12]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Hi @jarrodlucia! Please fill out the provided template when reporting an issue.

**Comment by jarrodlucia** [comment]
Apologies, meant to submit the information and got held up.

Problem/Motivation
Installed Grafana with Hass.io and followed the how to. The addon created a container and had no errors in the log.
iframe was created and redirect to grafana page successful.

Expected behavior
Dashboards and db source configured, as per main page.

Actual behavior
Once I opened Grafana, it was a blank instance, no sources, no dashboards nothing configured.

Steps to reproduce
install grafana addon via hass.io, navigate to granfana page.

![image](https://user-images.githubusercontent.com/11932876/45607202-15e12880-ba8e-11e8-92d4-2dad3702c160.png)

**Comment by tjorim** [comment]
That looks like a perfectly fine Grafana install. Do you want to use it with the InfluxDB add-on?
If yes, you'll need to follow these steps: https://github.com/hassio-addons/addon-grafana#using-it-with-the-influxdb-community-add-on
Please note there won't be any dashboards after this, you need to add your own.

**Comment by jarrodlucia** [comment]
Oh I see , yes I thought there were pre-developed dashboards that I expecting to see. Understood, thanks !
