### ISSUE TITLE
Dont save env_vars

### ISSUE THREAD

**Issue by SPEC1AL1ST** [hassio-addons/addon-grafana#121]
After update to 2021.3.3 i cant change env_vars in grafana config. They dont save it.

**Comment by frenck** [comment]
2021.3.3 is a Home Assistant Core version number, that doesn't have anything to do with add-ons.

Please provide the output of `ha info` thanks! 👍

**Comment by SPEC1AL1ST** [comment]
> 2021.3.3 is a Home Assistant Core version number, that doesn't have anything to do with add-ons.
> 
> Please provide the output of `ha info` thanks! 👍

How i can do it?

**Comment by frenck** [comment]
value is a string, not a boolean as shown in your video.

**Comment by SPEC1AL1ST** [comment]
But yesterday its working...

**Comment by frenck** [comment]
Its not the add-on that defines that interface. The add-on requires values to be a string. You put in  booleans...

That is a user configuration error; no matter if it worked on not.

**Comment by SPEC1AL1ST** [comment]
> Its not the add-on that defines that interface. The add-on requires values to be a string. You put in booleans...
> 
> That is a user configuration error; no matter if it worked on not.

But in the documentation you yourself give such an example.
https://c2n.me/4bfKQ5Z
What am I doing wrong then?

**Comment by frenck** [comment]
Please read about YAML and learn the differences between types.

```yaml
  - name: GF_AUTH_ANONYMOUS_ENABLED
    value: "true"
```
