### ISSUE TITLE
can't set env_vars: in addon configuration

### ISSUE THREAD

**Issue by aaronsb** [hassio-addons/addon-grafana#126]
# Problem/Motivation

> env_vars does not seem to pass the regex test and reverts to default from the JSON template

## Expected behavior

> my env_vars yaml should be accepted

## Actual behavior

> the text reverts to the JSON template for the addon configuration.

## Steps to reproduce

> observe the attached gif file
> on Home Assistant 2021.3.4
> on Grafana 6.2.0

![cant-set-vars](https://user-images.githubusercontent.com/2738471/112898294-40bc8680-90a6-11eb-94df-292b6777edf3.gif)

## Proposed changes

> I do not have a proposed change at this time.

**Comment by frenck** [comment]
Environment variables aren't type aware and always string. You've put in a boolean, which doesn't work indeed.

**Comment by aaronsb** [comment]
How do I set an environment value with the value of "true" without the data getting parsed as boolean?

The example in the documentation tab also does not parse.

**Comment by aaronsb** [comment]
Nevermind, single quotes. 'true'
Thanks for the response. 😅
