### ISSUE TITLE
After installing the addon with plugin grafana-googlesheets-datasource, plugin unavailable

### ISSUE THREAD

**Issue by antoweb** [hassio-addons/addon-grafana#141]
# Problem/Motivation
After installing the addon and configured with these parameters

plugins:
  - grafana-googlesheets-datasource
env_vars: []
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem

The addon is installed and also the plugin, but when configuring data source google sheet an error message appaer:
"Plugin Unavalable"

![image](https://user-images.githubusercontent.com/32364871/115136717-f5045980-a021-11eb-85c7-aec38a5d2df5.png)

> (Why the issue was filed)

Erorr log are:
t=2021-04-18T08:45:14+0200 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=grafana-googlesheets-datasource error="fork/exec /var/lib/grafana/plugins/grafana-googlesheets-datasource/dist/gfx_sheets_linux_arm64: no such file or directory"

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
It seems like this plugin is not compatible with arm-based machines. There is not much I can do about that from an add-on perspective.

You could try raising a feature request with the plugin authors? 🤷‍♂️ 

../Frenck 🚂

**Comment by antoweb** [comment]
Thanks asked to developer
