### ISSUE TITLE
Image renderer not working since 6.3.4

### ISSUE THREAD

**Issue by lbonherbe** [hassio-addons/addon-grafana#155]
# Problem/Motivation

Hello All! Since the upgrade to 6.3.4 the renderer doesn’t work anymore for me. If I click on share - direct rendered image I get a Grafana / Server Error saying “rendering failed”.

## Expected behavior

Same as before

## Actual behavior

fail

## Steps to reproduce

Just click on a dashboard, and select share rendered image

## Proposed changes

No idea...

More information:

This is the log from the add-on:

[15/May/2021:09:18:31 +0200] 200 -(172.30.32.2) GET /api/health HTTP/1.1 (Python/3.8 aiohttp/3.7.4.post0)
t=2021-05-15T09:19:07+0200 lvl=info msg=Rendering logger=rendering renderer=plugin path=“d-solo/RkwWjlcMz/consumption-appliances?orgId=1&from=1618471069791&to=1621063069791&panelId=2&width=1000&height=500&tz=Europe/Budapest”
t=2021-05-15T09:19:07+0200 lvl=eror msg=“Render request failed” logger=plugins.backend pluginId=grafana-image-renderer url=“http://localhost:3000/d-solo/RkwWjlcMz/consumption-appliances?orgId=1&from=1618471069791&to=1621063069791&panelId=2&width=1000&height=500&tz=Europe/Budapest&render=1” error=“Error: Failed to launch the browser process!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libxcb-dri3.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n”
t=2021-05-15T09:19:07+0200 lvl=eror msg=“Rendering failed.” logger=context userId=1 orgId=1 uname=admin error=“rendering failed: Error: Failed to launch the browser process!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libxcb-dri3.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n”
t=2021-05-15T09:19:07+0200 lvl=eror msg=“Request Completed” logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/RkwWjlcMz/consumption-appliances status=500 remote_addr=“192.168.2.208, 172.30.32.1” time_ms=11 size=768 referer=

I’m running HA 2021.5.4 on a NUC, everything is up to date and it used to work until the latest Grafana upgrade.
My Grafana add-on config is as follow:
plugins:

michaeldmoore-multistat-panel
env_vars:
name: GF_AUTH_ANONYMOUS_ENABLED
value: ‘true’
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem

**Comment by mamk95** [comment]
Experiencing the same problem. Temporary workaround is to downgrade using a previous snapshot. Remember to turn off auto update after the snapshot restore.

**Comment by anoblet** [comment]
I am also running into this error.

**Comment by anoblet** [comment]
@frenck Any chance you could take a look at this?

**Comment by lpriemis** [comment]
I Have the same issue. I tied changing the concurrent_render_limit from 5 to 30 (found some old links suggesting that) and concurrent_render_request_limit for good meassure, but it doesn't seem to work, Even tried 1000 but also no luck

I used ENV_VARs in de configuration TAB:

  - name: GF_ALERTING_CONCURRENT_RENDER_LIMIT
    value: '1000'
  - name: GF_RENDERING_CONCURRENT_RENDER_REQUEST_LIMIT
    value: '1000'

**Comment by IsaTTeN** [comment]
Same problem here
