### ISSUE TITLE
Allow plugin custom url

### ISSUE THREAD

**Issue by ohadlevy** [hassio-addons/addon-grafana#166]
# Problem/Motivation

Hello,

I would like to install a plugin such as grafana-map-panel which sadly not published "correctly"

the equivalant install command is using a custom plugin url

```
grafana-cli --pluginUrl https://github.com/panodata/grafana-map-panel/releases/download/0.15.0/grafana-map-panel-0.15.0.zip plugins install grafana-worldmap-panel-ng
```

## Expected behavior

Extend the configuration to allow passing the pluginUrl option

Thanks!

**Comment by frenck** [comment]
This has been requested before, and is not added.

Thanks for the suggestion.

**Comment by ohadlevy** [comment]
thanks for considering, is there any alternative?
