### ISSUE TITLE
Wish to upgrade grafana version to 5.4

### ISSUE THREAD

**Issue by klaasnicolaas** [hassio-addons/addon-grafana#17]
Could Grafana be upgraded to the 5.4 version? At the moment this version is still in `beta`, but brings a nice feature with it. From this version it is possible to use the graphical query editor for those who use a MySQL database. [More info](https://github.com/grafana/grafana/issues/13762)

**Comment by frenck** [comment]
Thanks, @klaasnicolaas, this, unfortunately, is currently blocked, since Grafana 5.4 is still in beta.

**Comment by frenck** [comment]
Grafana has been updated in the current edge branche. Will be part of the upcoming release.
