### ISSUE TITLE
Error on supervisor after Grafana 7 and core 2021.6.4

### ISSUE THREAD

**Issue by Cippo2019** [hassio-addons/addon-grafana#173]
Hello
first of all sorry for my bad English
After udate Grafana to 7 (on hassio 2021.6.4) i see each time when I open grafana this error :

21-06-14 19:46:21 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:1337/api/live/ws')

Grafana works perfectly but I have this error.

Also a friend of mine has the same problem 

thanks in advance for any kind of help

wbr
Tiziano

**Comment by tomlut** [comment]
This error is also present fro Grafana 7.0.1

**Comment by MS-Turbo** [comment]
Same issue here!

21-06-16 19:58:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:58:20 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:58:21 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:58:32 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:58:44 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:59:00 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:59:11 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:59:27 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:59:41 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 19:59:55 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:00:08 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:00:24 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:00:42 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:01:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:01:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:01:37 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:01:52 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:02:03 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:02:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:02:31 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:02:51 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:03:10 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:03:22 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')
21-06-16 20:03:37 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.1:1337/api/live/ws')

**Comment by MS-Turbo** [comment]
I got the errors after rebooting host. Can mention that I have another setup at another location, same hardware, plugins, versions and everything. I do not have this error in the logs at the other location.

**Comment by dragolea** [comment]
Same issue here, but in my case I cannot use HA anymore in the browser.

**Comment by emmost** [comment]
Hello, same issue here with HA 2021.6.5 and Grafana add-on 7.0.1

`21-06-18 05:31:57 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:1337/api/live/ws')`

**Comment by SmartM-ui** [comment]
Hi,
I also have the same error. 
When I open Grafana add-on, in the supervisor log I have this error, even though everything seems to work correctly:

21-06-18 08:04:36 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message = 'Invalid response status', url = URL (' http://172.30.33.3:1337/api / live / ws')
21-06-18 08:04:38 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message = 'Invalid response status', url = URL (' http://172.30.33.3:1337/api / live / ws')
21-06-18 08:04:40 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message = 'Invalid response status', url = URL (' http://172.30.33.3:1337/api / live / ws')

My Home Assistant OS:
Versione core-2021.6.5
Versione supervisor-2021.06.3
Sistema operativo Home Assistant OS 6.0
Grafana version: 7.0.1

**Comment by gabriele-latino** [comment]
Same errors here, my config:

core-2021.6.6
supervisor-2021.06.3
Home Assistant OS 6.0
Grafana 7.0.1

**Comment by ferropolis** [comment]
Same error here: 

Log Supervisor
`21-06-23 20:56:54 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.4:1337/api/live/ws')
21-06-23 20:56:58 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.4:1337/api/live/ws')
21-06-23 20:57:11 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.4:1337/api/live/ws')`

**Comment by mariusw** [comment]
I second this. Stopping the Grafana addon gets rid of those messages, but creates these instead:
`21-06-25 08:11:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:1337 ssl:default [Connect call failed ('172.30.33.3', 1337)]`

**Comment by gairom** [comment]
same error for me `21-06-26 01:25:58 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:1337/api/live/ws')`
Config:
supervisor-2021.06.6
core-2021.6.6
Grafana 7.0.1

**Comment by jdammers** [comment]
Same issue here. However, I only get these error messages when using the WEB UI of grafana for visualization. Once the WEB UI is closed, no more errors are reported in the supervisor logs.
 
My Config:
supervisor-2021.06.6
core-2021.6.6
Grafana 7.0.1

**Comment by phedoreanu** [comment]
@frenck any updates? The core log is spammed with errors.

**Comment by michael0731** [comment]
same error here.
21-07-02 17:38:25 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.3:1337/api/live/ws')

My System Health

version: core-2021.6.6
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.9
os_name: Linux
os_version: 5.10.17-v8
arch: aarch64
timezone: Asia/Taipei


GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.13.2
Stage: running
Available Repositories: 910
Installed Repositories: 7


host_os: Home Assistant OS 6.1
update_channel: stable
supervisor_version: supervisor-2021.06.6
docker_version: 20.10.6
disk_total: 116.5 GB
disk_used: 28.4 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.5.1), Duck DNS (1.12.5), NGINX Home Assistant SSL proxy (3.0.1), File editor (5.3.1), Git pull (7.12.2), Glances (0.12.2), Google Assistant SDK (2.5.0), Grafana (7.0.1), IDE (2.2.0), Mosquitto broker (5.1.1), Node-RED (9.1.4), RPC Shutdown (2.2), SQLite Web (3.1.0), TasmoAdmin (0.15.0), Let's Encrypt (4.11.0), Check Home Assistant configuration (3.7.1), AirCast (3.0.0), SSH & Web Terminal (8.2.4), Backup Hassio to Google Drive (1.7.9), Nginx Proxy Manager (0.11.0), MariaDB (2.3.0), phpMyAdmin (0.4.1), Network UPS Tools (0.7.0), InfluxDB (4.1.1)


dashboards: 1
resources: 5
views: 16
mode: storage

**Comment by jasonrwise77** [comment]
Can we get an update on this issue, please?

**Comment by FreakZAR** [comment]
Same here

Version core-2021.6.6
Version supervisor-2021.06.6
Grafana version: 7.0.1
InfluxDB version: 4.1.1
