### ISSUE TITLE
Home assistant becomes unresponsive after using grafana

### ISSUE THREAD

**Issue by arifroni** [hassio-addons/addon-grafana#174]
# Problem/Motivation

Since this morning (after an update (7.0.1)of grafana addon), when I try to plot a new graph --> select an entity, it shows 'loading options' and then HA becomes completely unresponsive. I waited 10 minutes and nothings changed. I need to power cycle the RPi to get it working again.

![chrome_2021-06-15_10-19-54](https://user-images.githubusercontent.com/59896374/122019374-fce33e80-cdc3-11eb-8d03-815f5cd454e9.png)

**Comment by frenck** [comment]
Sounds like you are pushing the limits on the RPi (usually in terms of memory). There is not much I can do about that.

**Comment by arifroni** [comment]
hmm, it can be the RAM, at 10:19 I tried to plot something, and ram usage was reported to be moving higher. 
what can cause this? size of infuxdb? how can I check the size of the database? what size is suitable for 4GB ram? is there any way I can reduce the size of the database? like, delete all entities which are not present in HA for the last 1 month?

![chrome_2021-06-15_13-18-28](https://user-images.githubusercontent.com/59896374/122043935-33c54e80-cddc-11eb-9a43-9e3417503038.png)

**Comment by frenck** [comment]
> size of influxdb?

Not just influx, more entities and data also mean more memory needed to process them (e.g., in Grafana).

> is there any way I can reduce the size of the database? like, delete all entities which are not present in HA for the last 1 month?

Yes, the influx DB integration in HA provides controls to filter what is send to Influx. Additionally, the retention can be controlled in Influx as well (on database level) or downsample by using continuous queries.

**Comment by arifroni** [comment]
the issue is not solved after updating to the latest version. as @frenck mentioned, this is caused by hardware limitations. I always noticed when I search for state in grafana, RAM, CPU usage jumps and HA stops responding. I am trying to move my grafana and influxdB to a different machine now.
