### ISSUE TITLE
addon is missing in HA

### ISSUE THREAD

**Issue by dddesign** [hassio-addons/addon-grafana#176]
I can't find grafana addon in my installed addons nor in available addons!
It could be (not sure 100%) that I installed grafana addon a long time ago, but never started it. since then I upgraded core and supervisor different times.

I already tried it by command line "HA addons reload" but with same result (no grafana addon to install)

do I understand something wrong?!

core-2021.6.6
supervisor-2021.06.3

**Comment by frenck** [comment]
Hi there @dddesign 👋 

That is odd, that should not happen. You could try adding our community repository manually, by adding this repository URL to the add-on store:

`https://github.com/hassio-addons/repository`

If the issue persists, I would recommend opening an issue with the Home Assistant project (Supervisor) and attaching logs for debugging.

Thanks! 👍 

../Frenck

**Comment by dddesign** [comment]
thanks a lot, this is working! see screenshots
![Bildschirmfoto 2021-06-22 um 16 16 52](https://user-images.githubusercontent.com/780871/122941364-9f2b9500-d375-11eb-98aa-716b0fb8a0eb.png)
![Bildschirmfoto 2021-06-22 um 16 17 13](https://user-images.githubusercontent.com/780871/122941399-a6eb3980-d375-11eb-9dd0-e1201d36c29d.png)

I'm still a little bit confused: should I get all community addons by a normal HA installation? or do I have to add this repo anyway?

**Comment by frenck** [comment]
> I'm still a little bit confused: should I get all community addons by a normal HA installation?

They should be there by default.
