### ISSUE TITLE
grafana-image-renderer, feature request

### ISSUE THREAD

**Issue by tjorim** [hassio-addons/addon-grafana#18]
# Problem/Motivation
The PhantomJS project has been abandoned and doesn't make sense to include it.
There's now a new "Grafana Backend Plugin that handles rendering of panels & dashboards to PNGs using headless chrome": https://github.com/grafana/grafana-image-renderer
Maybe this could be included in the add-on as a replacement.

Until now PhantomJS was still installed but didn't work that well (if at all).
Last time the argument was that the "Grafana Image Renderer" is kinda new and we're unsure if it would be the official Grafana thing. However, it will be default in 6.0 (see last posts in https://github.com/grafana/grafana/issues/13802) but it would be nice to have it before then.

## Expected behavior
Not expecting anything, but would be nice to see it included.

## Actual behavior
There is no way to have rendered images.

## Steps to reproduce
Try to use a rendered image.

## Proposed changes
Include the new headless chrome plugin and nodejs to run it in the docker image. One of the problems that's mentioned is it would break all server side rendering and alert images, but not really a problem since it didn't always work at the moment either.

<blockquote><img src="https://avatars2.githubusercontent.com/u/7195757?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/grafana/grafana-image-renderer">grafana/grafana-image-renderer</a></strong></div><div>A Grafana Backend Plugin that handles rendering of panels & dashboards to PNGs using headless chrome - grafana/grafana-image-renderer</div></blockquote>

**Comment by frenck** [comment]
This is pretty beta and not as easy as it seems.
It requires a second server to run on the add-on (the renderer).
I'm not sure if I can make it to include it into the next release.

**Comment by frenck** [comment]
I've investigated the possibility to use this and got pretty far.
Except: It isn't working / compatible with ARM yet, the main reason to install/use this in the first place.

**Comment by frenck** [comment]
The upstream issue seems to be blocked. Grafana 6 has been shipped already, still not change.

I'm closing this issue, not because I don't care, but mainly because there is nothing we can do about it from our end.
