### ISSUE TITLE
not able to connect to two influxdb on 2 physical devices , from one grafana 

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-grafana#2]
# Problem/Motivation

i do have two influxdb running on different physical  machines,  im using best libre addons , and on the process to migrate to your version (new).
this are my findings so far , ( may be a limitation on the addon , or maybe something im doing wrong) 
i can access both from the same grafana instance ( i tested with  your addon) and there is no problem on mixing of the "new" ingluxdb data ( running on the same rPI as the new grafana) with the old influxdb running on rpi1 .

but , i cant get access to the new influxdb , from the rpi1 which is running the other  grafana instance .

So, i can access best libre influxdb, from any, but the new influxdb , only from the grafana running on the same physical device.

will the data base on the other device have a different address?   than  http://a0d7b954-influxdb:8086 , should we use the docker host IP address? as the address should be different for both ...

is it possible to get access to the db on the container , from outside the container ?,

## Expected behavior
be able to access two different influxdb from one grafana instance.

## Actual behavior

as mentioned, not able to get access to the db inside the container from other device.

## Steps to reproduce

install influxdb on 2 different machines , and grafana on either , and try to configure grafana to connect to both at the same time .

**Comment by frenck** [comment]
Yes it is possible to access InfluxDB from outside the container on a device in the same network. Simply use the IP of the device (e.g. the 192.168.x.x IP of the pi1) to connect to.

The `2452442-influxdb` kinda hostnames only work on the device itself. It refers to an internal network running between the add-ons and thus will only work on the same machine.

**Comment by gnkarn** [comment]
Ok, perfect , thanks
