### ISSUE TITLE
enable auth.anonymous

### ISSUE THREAD

**Issue by newbee112** [hassio-addons/addon-grafana#23]
# Problem/Motivation

>enable auth.anonymous=true to remove need to login prompt for iframe share in for example lovelace. 

## Expected behavior

> able to modify this variable in addon "config" 

## Actual behavior

> not available

## Steps to reproduce

> N/A

## Proposed changes

> add auth.anonymous as option in grafana hassio addon config

**Comment by frenck** [comment]
That is already provided using this option:

https://github.com/hassio-addons/addon-grafana#option-env_vars

**Comment by newbee112** [comment]
thanks!! i did not get that. 
works like a charm: 
  "env_vars": [
    {
      "name": "GF_AUTH_ANONYMOUS_ENABLED",
      "value": "true"
    }
  ]
