### ISSUE TITLE
not able to login from embeded link or panel

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-grafana#25]
# Problem/Motivation

> after updating to lattest version  even when the addon works fine, and able to login to the web interface , it does not work when trying to login from a panel link view or an embeded link . it just stays on the login screen and even when it is accepting credentials ( i see a fast green blink --> login ok) , it just stays asking for login .

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by gnkarn** [comment]
i have configured the auto login by setting env variable as follows:

``
{
      "name": "GF_AUTH_OAUTH_AUTO_LOGIN",
      "value": "true"
    }
``
but is not working and the following error is on the logs

lvl=warn msg="Skipping OAuth auto login because multiple OAuth providers are configured."

and can not go beyond the login page , from lovelace iframe or pannel.

the only way i can get into grafana now is by going directly to the URL.

**Comment by frenck** [comment]
That options sets Grafana to try to log in using OAuth automatically.
How did you set up your OAuth proxy?

**Comment by Fury1SOG** [comment]
Hello,
I have the same problem as OP.
Here are my Config settings:
```
{
  "log_level": "info",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "plugins": [
    "grafana-clock-panel",
    "natel-discrete-panel"
  ],
  "env_vars": []
}
```

**Comment by JaumeMuste** [comment]
Same problem here, unable to login to this addon when it is configured into an ipanel.
In my config ssl is set to false

**Comment by pdecat** [comment]
This was fixed for me in v2.0.0 of the grafana addon.

**Comment by pdecat** [comment]
> This was fixed for me in v2.0.1 of the grafana addon.

Or not... This works on Chrome for Android but still not with Chrome / Firefox on Ubuntu.

**Comment by Fury1SOG** [comment]
On MacOS 10.14.3, the Grafana login works correctly from ipanel on Firefox, but not on Safari and Chrome

**Comment by frenck** [comment]
There has been an issue with some chrome based browsers and this type of authentication, please make sure you are running the latest version of Chrome and try again.

**Comment by pdecat** [comment]
Issue still present on Ubuntu 18.10 64bit with:
- Google Chrome stable version 73.0.3683.86
- Mozilla Firefox 66.0.1

**Comment by pdecat** [comment]
The issue I was facing on Chrome and Firefox desktop with the new version of the grafana addon was triggered by the fact that the iframe was configured using the IP address of the host:


```
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: 192.168.1.5
```

However, I was accessing the Home Assistant UI from http://hassio.local

On my mobile, I did not face the issue because I was accessing HA using the IP address.

Changing the configuration to the following works around the issue:
```
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: hassio.local
```

Strange thing is that the same behavior does not happen with the influxdb addon.

**Comment by dddesign** [comment]
same for me here: if pael_iframe and lovelace iframe is configured with hassio.local it's working when accessing by hassio.local but not by y.our.ip and vis versa. would be great if we can configure it in a way that you can accessing by hassio.local AND y.our.ip

**Comment by frenck** [comment]
There are some big changes around this in the latest release of the add-on. Please try again to see if it solves your issue.

**Comment by Mace404** [comment]
Seems like the datasource password is not getting saved properly between restarts.
Go to your data source, hit the reset button at the password field and enter the password again.
That solves the login box for me... until the next restart.

**Comment by jfael** [comment]
> Seems like the datasource password is not getting saved properly between restarts.
> Go to your data source, hit the reset button at the password field and enter the password again.
> That solves the login box for me... until the next restart.

I had the same issue.
After reseting the data source password it's working again.
Thanks

**Comment by frenck** [comment]
Release Grafana add-on v2.2.2 that addresses most issues around passwords, secrets and datasources.

**Comment by FlavorFx** [comment]
Same issue here. Login with Chrome works fine but failed with Safari on Mac. Grafana add-on 2.2.3. Any ideas?
