### ISSUE TITLE
Plugins installation from Plugins Catalog is disabled

### ISSUE THREAD

**Issue by Al-Dek** [hassio-addons/addon-grafana#262]
# Problem/Motivation
Installation of  plugins from Grafana catalog is disabled.
No changes were made in the configuration of the HA and Grafana. The problem appeared after restarting the HA server a month ago. I looked through everything I could find on this topic, but I didn't find anything and couldn't find in the Grafana documentation what this message means
Gtafana itself has access to the Internet and gtafana.com . 
## Expected behavior
As it was before - catalog was accessible. 

## Actual behavior
After opening Grafana addon GUI and trying to open plugins catalog on Grafana server message appears:
"_This filter has been disabled because the Grafana server cannot access grafana.com_"
The screenshot is attached.
Sys info and Grafana log and config are attached.

## Steps to reproduce
I have no idea...

## Proposed changes
Any fixup, advise, whatever to eliminate  this trouble
[Grafana_cfg.txt](https://github.com/hassio-addons/addon-grafana/files/8565507/Grafana_cfg.txt)
[Grafana_log.txt](https://github.com/hassio-addons/addon-grafana/files/8565508/Grafana_log.txt)
[HA_sys_info.txt](https://github.com/hassio-addons/addon-grafana/files/8565570/HA_sys_info.txt)

**Comment by asyvan** [comment]
Have the same issue. Can only view already installed plugins, filter "All" not accessible with the same error as described above.

**Comment by asyvan** [comment]
The workaround is to add the plugin under Home Assistant -> Configuration -> Add-ons -> Grafana -> Configuration
There is a option called 'plugins', there you just type the name of the plugin as it's displayed on the plugin page on the web. Restart Grafana, refresh browser. Done.
![image](https://user-images.githubusercontent.com/2380800/167684468-624ac815-15f2-4f65-8bee-2a0ae5f9fa73.png)

**Comment by Al-Dek** [comment]
@asyvan  Thaks a lot!
We зProposed the same solution together.
See my post above yours.
))

**Comment by frenck** [comment]
👀 <https://github.com/hassio-addons/addon-grafana/blob/main/grafana/DOCS.md#option-plugins>
