### ISSUE TITLE
Grafana loses all of my dashboards after my system is rebooted.

### ISSUE THREAD

**Issue by Billium28** [hassio-addons/addon-grafana#269]
# Problem/Motivation

I have Home Assistant on a VM Linux from HA hompage. I have both Grafna and InfulxDB installed inside HA as an addon, this addon. This is running on Unraid. Unraid and HA have been rock solid for years. I have Grafana and Influx talking to each other.  When I reboot my Unraid server, after an update or restart of PC, my Grafana dashboards are all gone and missing. It seems Grafana and Influx stil see eachother.

Someone mentioned I do not have persistant storage for Grafana, is this true?

**Comment by frenck** [comment]
> Someone mentioned I do not have persistant storage for Grafana, is this true?

This is not something you should have to worry about with add-ons.

How have you installed it in Unraid?
Could you provide me the output of `ha info`?

**Comment by Billium28** [comment]
Sorry I just now saw you replied. I have Grafana installed using HACs, as far as I can tell the standard way. How do I supply the output of ha info?
