### ISSUE TITLE
Upgrade is very welcome

### ISSUE THREAD

**Issue by p0wertiger** [hassio-addons/addon-grafana#277]
# Problem/Motivation

Grafana 8.5 release is currently at 8.5.10 while this add-on is stuck on version 8.5.3

## Expected behavior

Grafana version gets upgraded at least to 8.5.10, most welcome to 9.0 or 9.1 branch.

## Actual behavior

Stuck at version 8.5.3

## Steps to reproduce

Install the add-on

## Proposed changes

Upgrade the version of Grafana. From my experience on standalone set-up, upgrades inside 8.5 line are seamless. Going to 9.x brings a bit of changes on user-side, there's a compatibility layer in Grafana for graphs.

**Comment by QuentinBtd** [comment]
https://github.com/hassio-addons/addon-grafana/pull/275 😁

**Comment by p0wertiger** [comment]
Yes I saw it after posting. Also, that's a PR and was missing an accompanying issue 😉 Anyway, I wish it was merged. In the end every contribution should be welcome.

**Comment by QuentinBtd** [comment]
Hi

Grafana addon is now running Grafana v9.1.5 

:)
