### ISSUE TITLE
Can no longer send alert messages via smtp

### ISSUE THREAD

**Issue by mauriceatkinson** [hassio-addons/addon-grafana#284]
I configured Alerting contact points with an email notification in Grafana several months ago and when an alert was triggered it fired off an email notification and it worked like a dream.  But as I was busy I turned this feature off.  Today I have come back and reactivated email alerts but I now receive a message stating the emails could not be sent.  

When configuring contact points you have the ability to test the send notification and get a confirmation the email has been sent.
However now I receive the message "failed to send test alert: failed to send notification to email addresses: yyy@xxxx.com EOF:"
(yyy@xxxx.com replaces real email address)

My Grafana smtp configuration uses gmail and I use the Google app authentication.  This has been tested using another service and the gmail service works as expected.

The Grafana error log shows the following message after the test send notification in contact points has been clicked.

logger=alertmanager org=1 t=2022-10-25T18:40:00.801001279+01:00 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="grafana-default-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: failed to send notification to email addresses: yyy@xxxx.com: EOF"

My Grafana config is as follows:
env_vars
- name: GF_SMTP_ENABLED
  value: "true"
- name: GF_SMTP_HOST
  value: smtp.gmail.com:587
- name: GF_SMTP_USER
  value: myemail@googlemail.com
- name: GF_SMTP_PASSWORD
  value: mypassword
- name: GF_SMTP_SKIP_VERIFY
  value: "true"
- name: GF_SMTP_FROM_ADDRESS
  value: myemail@googlemail.com
- name: GF_SMTP_FROM_NAME
  value: GRAFANA

any ideas as to the problem?

**Comment by flecmart** [comment]
I have the same problem just noticed this today. Unfortunately I cannot say since when this occured but it definately worked previously. I also tried to switch to webhook notifications via access token bearer authentication but that I also cannot get to work within Grafana.

**Comment by flecmart** [comment]
Not stale for me. However I worked around and use notifier together with https://github.com/pinpox/home-assistant-grafana-relay now. 

Can recommend it.

**Comment by mauriceatkinson** [comment]
this is not stale and it is an outstanding issue
