### ISSUE TITLE
Grafana addon won't install

### ISSUE THREAD

**Issue by PeterKawa** [hassio-addons/addon-grafana#290]
# Problem/Motivation
> Grafana addon won't install
`Home Assistant 2022.12.6 
Supervisor 2022.11.2 
Operating System 9.4 
Frontend 20221213.0 - latest`

## Expected behavior

> A nice Grafana dash 

## Actual behavior

> The install procedure errors after a (long) while: 
`Can't install ghcr.io/hassio-addons/grafana/amd64:8.1.0: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/hassio-addons/grafana/amd64:8.1.0/json: Not Found ("no such image: ghcr.io/hassio-addons/grafana/amd64:8.1.0: No such image: ghcr.io/hassio-addons/grafana/amd64:8.1.0")
`
## Steps to reproduce

> Create a VirtualBox VM on linux Debian 11,  download the VM image @ https://github.com/home-assistant/operating-system/releases/download/9.4/haos_ova-9.4.vdi.zip and when after you created your account, login and try to install Grafana Add-On. I got the error mentioned above.
The same error happens while trying to install StudioCodeServer, Node-Red
I managed to install the File Editor. 
The Terminal & SSH addon installs, but won't run in any way
I tried it with a fresh VM, while my current HA instance had the same issues. 

## Proposed changes

> Not a clue

**Comment by sinclairpaul** [comment]
This is usually caused either by DNS issues (which isn't likely as one addon installed), or disk space issues.  Either way it isn't related to the addon as you get the same issue with other installs.

I would suggest you reach out on the HA forums or Discord for assistance.
