### ISSUE TITLE
Unable to add configuration overrides

### ISSUE THREAD

**Issue by CeeBeeEh** [hassio-addons/addon-grafana#294]
# Problem/Motivation

I want to change the default date display formats.

## Expected behavior

Add the variable to the env_var field

## Actual behavior

Cannot save the settings

## Steps to reproduce

Add a custom config override, such as:

`- name: interval_month`
`  value: 'YYYY-MM'`

## Proposed changes

Do not check variables to be only for security settings

**Comment by sinclairpaul** [comment]
As per the documentation: https://github.com/hassio-addons/addon-grafana/blob/main/grafana/DOCS.md#option-env_vars

```Note: _Only environment variables starting with GF_ are accepted._```

Please look at the Grafana documentation on variables as yours will likely be:

``GF_DATE_FORMATS_INTERVAL_MONTH```
