### ISSUE TITLE
Since updating to 8.2.0 the plugin is complaining about a colon in the URL and all dashboards are empty

### ISSUE THREAD

**Issue by Fridolin34** [hassio-addons/addon-grafana#308]
# Problem/Motivation

> Since two years, the grafana plugin worked like a charm. Just after the last update, all dashboards are empty and I get the following error when I test the connection: 
"parse "192.168.2.29:8086": first path segment in URL cannot contain colon error creating influxDB healthcheck request"
The log of the addon says: 
"logger=context userId=1 orgId=1 uname=admin t=2023-03-08T21:44:34.741509663+01:00 level=error msg="Internal server error" error="[plugin.downstreamError] failed to query data: parse \"192.168.2.29:8086\": first path segment in URL cannot contain colon" remote_addr=192.168.2.27 traceID="

## Expected behavior

> Nothing has changed concerning the configuration or the network, so the connection should be possible.

## Actual behavior

> Nothing is shown anymore

## Steps to reproduce

> Just take a look at the dashboards.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by baztuk** [comment]
Hi Fridolin,
check your data source in Grafana. You should get an error with the URL.
http://192.168.2.29:8086 instead of 192.168.2.29:8086 should fix the problem

**Comment by Fridolin34** [comment]
@baztuk Thanks a lot for your comment. I've tried that already, but it does not seem to work either. Just the error is different: 

"Post "http://192.168.2.29:8086/query?db=homeassistant&epoch=ms": net/http: invalid header field name "" error performing influxQL query"

**Comment by mahlzeit1948** [comment]
had the exact same error and baztuk's advice worked for me

**Comment by Fridolin34** [comment]
I gave it another try, added the http prefix and removed  the custom HTTP headers in the edit data source page. The idea to do this has been discussed here: https://community.grafana.com/t/error-after-update-plugin-and-restart/52267

I never added customer headers manually and I would expect that a migration script would take care of no longer needed or even unhealthy properties, but okay. At least it is working again.
