### ISSUE TITLE
No data --> Influx DB Protocol sheme

### ISSUE THREAD

**Issue by smoki3** [hassio-addons/addon-grafana#310]
Hi since the latest home assistant update I get the following issue

`Post "a0d7b954-influxdb:8086?db=&epoch=ms": unsupported protocol scheme "a0d7b954-influxdb" error performing influxQL query`

So looks like grafana is not able to connect to the influx db. And due to this my dashboard doesn't show any data. I dont changed anything to the configuration. 

![image](https://user-images.githubusercontent.com/9723729/225268684-5b0a3e47-f9c1-4cb2-b450-714d2f08f64e.png)

**Comment by qwertyphile** [comment]
getting the same error

**Comment by qwertyphile** [comment]
Update to Grafana 8.2.1 and InfluxDB 4.6.0 plugins fixed the issue for me... seems this bug may have been an issue with the nginx web server library used in these plugins.
