### ISSUE TITLE
Error upgrade/installing addon-grafana 8.2.2

### ISSUE THREAD

**Issue by davecpearce** [hassio-addons/addon-grafana#320]
# Problem/Motivation

I was previously running v 8.2.1 and I was not able to successfully upgrade to 8.2.2.  I removed the addon and attempted to re-install but I am getting the following error:

Failed to to call /addons/a0d7b954_grafana/install - Can't install ghcr.io/hassio-addons/grafana/amd64:8.2.2: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/hassio-addons/grafana/amd64:8.2.2/json: Not Found ("No such image: ghcr.io/hassio-addons/grafana/amd64:8.2.2")

## Expected behavior

I was expecting the upgrade from 8.2.1 to 8.2.2 to be successful or be able to remove and re-install the Gradana add-on

## Actual behavior

The upgrade/install is failing.  This message is written to the log file:

Failed to to call /addons/a0d7b954_grafana/install - Can't install ghcr.io/hassio-addons/grafana/amd64:8.2.2: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/hassio-addons/grafana/amd64:8.2.2/json: Not Found ("No such image: ghcr.io/hassio-addons/grafana/amd64:8.2.2")

## Steps to reproduce

Attempt to upgrade to 8.2.2 from a previous version or un-install and re-install Grafana

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> Failed to to call /addons/a0d7b954_grafana/install - Can't install ghcr.io/hassio-addons/grafana/amd64:8.2.2: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/hassio-addons/grafana/amd64:8.2.2/json: Not Found ("No such image: ghcr.io/hassio-addons/grafana/amd64:8.2.2")

This is not an add-on issue, but an issue with your system.

You could try running `ha supervisor repair`

../Frenck
