### ISSUE TITLE
/init: 37: exec: s6-overlay-suexec: not found

### ISSUE THREAD

**Issue by allanicars** [hassio-addons/addon-grafana#322]
# Problem/Motivation

> starting a new installation of Home assistant...  when I try and start grafana I get the above error

## Expected behavior

on startup after installation

## Actual behavior

nothing.. just error

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Anyone come across this or know a fix ?

**Comment by frenck** [comment]
How did you install/run it? Could you provide some more information?

Thanks! 👍 

../Frenck

**Comment by allanicars** [comment]
Hi,

I installed it from the add on store….
Went through the config as described by the video
https://www.youtube.com/watch?v=1QS-eDVjdiY&ab_channel=RobertoJorgeTech%28English%29

and then tried to start it…

that’s when I see the error…. Under the log tab

Can’t seem to see any other errors…..  but looking.

Regards

Allan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by allanicars** [comment]
Pc running Win10
has Oracle Virtualbox 7.06
HA10.1   fresh install
loaded HACS, Terminal & SSH, File editor and InfluvDB.... (and setup as described in videos/tutorials)
then downloaded grafana...  tried to start... got error

looked around and cannot seem to find anyone with the error, hence posting on here

**Comment by allanicars** [comment]
after several deletions and reinstalls of grafana...   its now working.....     go figure ???
