### ISSUE TITLE
grafana not starting correctly after update

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-grafana#33]
# Problem/Motivation

GRafana web page  not being served after update to 2.1.0

all starting logs seams correct and no errors , ( plugins register process is ok, all initialization is ok) 
it won't open the ui after clicking the Web ui button  , error is 
`404 Site my_ip  is not served on this interface`

and this is the last line on the grafana logs :

`t=2019-04-25T17:08:48-0300 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:80 protocol=http subUrl= socket=`
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
updated the add-on , restarted hassio , use the web button, or directly the ip:3000 

> (How can someone else make/see it happen)

## Proposed changes
my config is 

```

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3
timezone | America/Argentina/Buenos_Aires
version | 0.92.0
virtualenv | false

```

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by gnkarn** [comment]
tried rebooting, but the problem remains ,very strange  grafana seams to be working in the background , but no way to access is GUI frontend with the usual ip:port .

**Comment by frenck** [comment]
please provider your full add-on config.

**Comment by amaximchuk** [comment]
I have the same issue. When rollback to 2.0.2 - everything ok

**Comment by gnkarn** [comment]
> {
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "plugins": [
    "ayoungprogrammer-finance-datasource",
    "grafana-clock-panel",
    "savantly-heatmap-panel",
    "briangann-gauge-panel",
    "natel-plotly-panel",
    "natel-discrete-panel"
  ],
  "env_vars": [
    {
      "name": "GF_DEFAULT_INSTANCE_NAME",
      "value": "Hassio"
    },
    {
      "name": "GF_ALLOW_SIGN_UP",
      "value": "true"
    },
    {
      "name": "GF_AUTH_OAUTH_AUTO_LOGIN",
      "value": "true"
    }
  ],
  "log_level": "info"
}

**Comment by gnkarn** [comment]
exactly , i stayed now in 2.0.2 .

**Comment by tmonck** [comment]
any updates on this? I'm on the latest version that was just released v2.1.1. I am unable to access the web ui. @frenck is there anything I can provide to help with debugging on my hassio? 

my config is:
`{
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "plugins": [],
  "env_vars": [],
  "log_level": "info"
}`

I am running on a custom port.

**Comment by tmonck** [comment]
@frenck I managed to figure it out. For some reason the Addon config page wasn't updated to show the new port that the container was listening on. So I clicked reset to defaults which fix the port mapping. I then adjusted to my custom port. Restarted after each change to the port. Now I am able to access the UI. I don't think it's anything wrong with the add on itself.

**Comment by gnkarn** [comment]
i tested again ( without any other modification) now with 2.1.1 and it works fine , thanks
