### ISSUE TITLE
Grafana fails to display with multiple browsers behind cloudfared

### ISSUE THREAD

**Issue by philbert** [hassio-addons/addon-grafana#332]
# Problem/Motivation

Grafana fails to display with multiple browsers behind cloudfared with the following error:
![image](https://github.com/hassio-addons/addon-grafana/assets/5618563/9b449e16-f901-49f7-83b5-cbd81174e998)
The only browser I have not encountered the same error on is Chrome.

Tested versions:
- Home Assistant 2023.5.4 
- Supervisor 2023.04.1 
- Operating System 10.2 
- Frontend 20230503.3 - latest 
- Firefox 114.0b9 and 110.0b4
- Safari Version 16.5 (18615.2.9.11.4) and Version 16.4 (18615.1.26.11.23)
- Microsoft Edge 113.0.1774.57 
- MacOS Ventura 13.4
- addon-grafana 8.3.0
- cloudflared 4.1.6

The specific error from firefox is this:
`Uncaught SyntaxError: identifier starts immediately after numeric literal /api/hassio_ingress/hO7ODvUpaIuTffaVzVbrsvYPD7iIVSe5c9JGgc3AkIo/public/build/7490.cf2da2a42f577bdb1843.js:187:4516`

In Safari it is this:
`SyntaxError: No identifiers allowed directly after numeric literal /api/hassio_ingress/hO7ODvUpaIuTffaVzVbrsvYPD7iIVSe5c9JGgc3AkIo/public/build/7490.cf2da2a42f577bdb1843.js:187`

Here is the offending file from Firefox (with the problem) and from Chrome (without the problem)
[Firefox.7490.cf2da2a42f577bdb1843.js.txt](https://github.com/hassio-addons/addon-grafana/files/11623839/Firefox.7490.cf2da2a42f577bdb1843.js.txt)
[Chrome.7490.cf2da2a42f577bdb1843.js.txt](https://github.com/hassio-addons/addon-grafana/files/11623856/Chrome.7490.cf2da2a42f577bdb1843.js.txt)

I did not upload the file from Safari because the offending line looks the same as it does in Firefox.

Looking at line 187 character 4516 in Firefox.7490.cf2da2a42f577bdb1843.js.txt which is the `.`
```
T.exports=i(1.valueOf)}
             ^
```

Compare this with line 198 in character 4516 in Chrome.7490.cf2da2a42f577bdb1843.js.txt, which is a space ` `
```
T.exports=i(1 .valueOf)}
             ^
```

Further notes:

- The error does not occur when viewing grafana on any of the browsers via my local LAN on `http://homeassistant.local:8123`
- There are no errors in the grafana log file after following the directions to increase the logging level to debug following directions here: https://github.com/hassio-addons/addon-grafana/blob/main/grafana/DOCS.md#option-log_level
- I also tried to change the default dashboard in grafana to a different one to see if there might be something about my specific graphs, but that also did not affect the result.
- The error does not occur in the mobile app.
- The error *does* occur in Safari, Firefox Focus and Chrome on mobile. (iOS 16.3)

## Expected behavior

I expect the dashboard to be displayed

## Actual behavior

I get the error "If you're seeing this Grafana has failed to load its application files"

## Steps to reproduce

The error looks reasonably platform independent. Install HA OS, Grafana and setup the Cloudfare tunnel. I don't believe it should be necessary to have any graphs configured.

## Proposed changes

Find and fix the offending numeric literal
Work around is to use the mobile app, or use the local connection.

**Comment by kanersps** [comment]
Update: re-installing resolves the issue, unsure for how long. Will report back if it breaks again, it's also quite simple to get backup and running, just export your dashboards and re-import them.

**Comment by philbert** [comment]
This issue seems to have disappeared since the release of the 9.0.0 addon
