### ISSUE TITLE
MQTT Datasource is not working

### ISSUE THREAD

**Issue by guenter-ms** [hassio-addons/addon-grafana#349]
# Problem/Motivation

> I need to display realtime live data in grafana using MQTT Datasource

## Expected behavior

> Receive data from MQTT Datasource

## Actual behavior

> Datasource can be generated and connection Test is OK, but no data can be received

## Steps to reproduce

> simply create a MQTT Datasource and connect to any MQTT Broker

## Proposed changes

> need a fix to make it work or a hint, what is wrong

See all details in this discussion: https://github.com/hassio-addons/addon-grafana/discussions/348

THANK YOU for help

**Comment by guenter-ms** [comment]
Any news?

**Comment by Thyraz** [comment]
Would also love to see this. 
Streaming live data into Grafana is a very cool feature. 

Will try to move my Grafana installation out of HA to somewhere else in the meantime. 

Thanks
