### ISSUE TITLE
Connection rejected from pannel or embebed link

### ISSUE THREAD

**Issue by IsaTTeN** [hassio-addons/addon-grafana#38]
# Problem/Motivation

I can't access Grafana form panel or embebed link

## Expected behavior

Access like before

## Actual behavior

I can access outside Hassio https://mysite.duckdns.org:3000/d/Be4Qfqggz/principal?orgId=1

## Steps to reproduce

Upgrading to last version

## Proposed changes

...

After last update Grafana stops to work just indide Hassio, It was working ok till now.

I´m having this error:
`t=2019-06-03T01:03:28+0100 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:80 protocol=https subUrl= socket=
2019/06/03 01:03:47 http: TLS handshake error from 192.168.1.10:55971: remote error: tls: unknown certificate`

Inside Hassio I have this:

![image](https://user-images.githubusercontent.com/20249994/58769187-71136680-859c-11e9-984a-eaf1709ca639.png)

With a message of rejected conection

This is my config:

`{
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "plugins": [],
  "env_vars": [
    {
      "name": "GF_AUTH_BASIC_ENABLED",
      "value": "false"
    },
    {
      "name": "GF_AUTH_PROXY_ENABLED",
      "value": "false"
    },
    {
      "name": "GF_AUTH_ANONYMOUS_ENABLED",
      "value": "true"
    },
    {
      "name": "GF_AUTH_ANONYMOUS_ORG_NAME",
      "value": "Main Org."
    },
    {
      "name": "GF_AUTH_ANONYMOUS_ORG_ROLE",
      "value": "Editor"
    },
    {
      "name": "GF_USERS_ALLOW_SIGN_UP",
      "value": "false"
    }
  ]
}`

**Comment by mrneilix** [comment]
Ditto. Just started happening to me today too

**Comment by BlueBlueBlob** [comment]
6.2 different config :
[Removed] Session setting was removed in v6.2, use remote_cache option instead"

Session used memcached and remote_cache is set as default : database.

But I don't know the memcached connection string

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/58795189-5079f980-85fa-11e9-9557-e6ffe210a0eb.png)

**Comment by frenck** [comment]
Seems like Grafana is sending out new headers preventing iframe to work.

**Comment by BlueBlueBlob** [comment]
I tried with : { "name": "GF_SECURITY_ALLOW_EMBEDDING", "value": "true" }
But no success

**Comment by frenck** [comment]
@BlueBlueBlob testing a new version right now on a local dev.

**Comment by BlueBlueBlob** [comment]
Thx.
I think some settings moved from session to another section. See doc and warning message.
Good luck 👍

**Comment by frenck** [comment]
@BlueBlueBlob That is a different issue. I would appreciate if we could keep things on topic and in focus. Thanks.

**Comment by frenck** [comment]
The issue has been addressed, will be fixed in the next release of the add-on.

**Comment by IsaTTeN** [comment]
Good!!!
