### ISSUE TITLE
Include fix from upstream for suddenly oversized graphs

### ISSUE THREAD

**Issue by markusdd** [hassio-addons/addon-grafana#381]
This is related to:
https://github.com/grafana/grafana/issues/80803

I am observing this behavior since last update of Grafana from Home Assistant (am on latest released version).

Is there a chance we can get a new build pushed with the bugfix mentioned in the ticket linked above?

Because my dashboard is currently messed up:
![grafik](https://github.com/hassio-addons/addon-grafana/assets/25175069/39ccfcf2-9fbe-494e-8a2a-b0c86d4d59df)

This is what it should look like:
![grafik](https://github.com/hassio-addons/addon-grafana/assets/25175069/73b44fb5-5083-40f0-b0bf-4f3b6451cf23)

**Comment by sinclairpaul** [comment]
It will be added when rolled into a release.

**Comment by markusdd** [comment]
can we then maybe get a rollback?

Because all dashboards that use these graphs are now bricked. This is not a small issue.

**Comment by sinclairpaul** [comment]
Rollback should be done by restoring snapshots.

**Comment by markusdd** [comment]
I am talking about a version rollback of grafana in the plugin.

I will not roll back my instance and all data because of this, certainly not.

**Comment by sinclairpaul** [comment]
You can restore the addon specific backup via the HA tools.

**Comment by markusdd** [comment]
I did that now and it indeed restores the graphs to correct state at version 9.1.1 .
This killed some settings but I can load them back in via file.

nevertheless would consider pulling the latest version of the plugin as it makes any dashboard using these (pretty common) graphs either ugly or completely useless. (or make a fix release with the patch).

Have spotted complaints in other Discord channels already, so it is likely you will get potentially flooded with similar tickets soon when people upgrade.

Anyway, thanks for the quick repsonses.
