### ISSUE TITLE
After installation cannot start grafana

### ISSUE THREAD

**Issue by Patbonamy** [hassio-addons/addon-grafana#389]
# Problem/Motivation

After insatallation Grafana won't start : "Failed to to call /addons/a0d7b954_grafana/start - Another job is running for job group container_addon_a0d7b954_grafana"
Same error if I want to uninstall

Home assistant is installed in a Promox Virtual Machine

**Comment by tjorim** [comment]
Try a full host reboot.

**Comment by Patbonamy** [comment]
> Try a full host reboot.

Thanks tjorim, I unpower my NUC and after power again Grafana start.
Do you know why ?

**Comment by tjorim** [comment]
Seems like the supervisor got stuck doing something.

**Comment by Patbonamy** [comment]
OK, thanks.
Have a good day
