### ISSUE TITLE
Missing plugins after Grafana updates 

### ISSUE THREAD

**Issue by t3lmoazevedo** [hassio-addons/addon-grafana#396]
# Problem/Motivation

Everytime I update Grafana, I loose my plugins (example: JSON API) and must install it again after the update.
Is there a way to keep plugins always installed? Or the problem is mine and I'm missing an extra setup anywhere?
Thanks for the help!

![image](https://github.com/hassio-addons/addon-grafana/assets/41584793/83178cd3-515a-4cc7-96a9-2cf39b6ff618)

**Comment by sinclairpaul** [comment]
Will close this out, Containers are ephemeral, so when you restart them they go back to the built state.  I'm assuming that's what is happening here, if you specify the plugin in the config it will get applied on every startup.
