### ISSUE TITLE
Make grafana plugins to survive a restart

### ISSUE THREAD

**Issue by lldaedalusll** [hassio-addons/addon-grafana#405]
# Problem/Motivation

I am using the clock plugin in grafana. With each grafana addon restart I have to reinstall that plugin.

## Expected behavior

The plugin remains installed even after restart.

## Actual behavior

All plugins are gone after a restart.

## Steps to reproduce

- install Clock plugin in grafana addon
- restart grafana addon
- notice that clock plugin is no longer installed

## Proposed changes

This is propably down to docker directory mapping / sharing / forwarding. I am no expert here, so I can't make suggestions. But I expect that there most propably is a plugin directoy which needs to allow changes to become persistent over addon restarts.

**Comment by frenck** [comment]
This is actually done by design, if an update causes issues (for example, could be anything else) that causes problems, you'll be able to remove it from the configuration.
