### ISSUE TITLE
Warning about google legacy API every minute in log

### ISSUE THREAD

**Issue by dpgh947** [hassio-addons/addon-grafana#427]
# Problem/Motivation

> (Why the issue was filed)
I updated the addon this morning (10.2.0) and so was looking in the log, and I am seeing this message every minute:
```
logger=oauth.google t=2024-11-12T10:52:07.274510458Z level=warn msg="Using legacy Google API URL, please update your configuration"
```
I don't have any plugins, don't have google oauth (or anything else) configured under admin/authentication, so I don't understand why this is being issued or how to stop it. It was there before this morning's update, but no sign of it without looking in the log, everything was and still is working fine.

This is obviously creating a lot of log output over time, and with the latest log viewing changes in HA I can see there are PAGES AND PAGES of this going back, I have no idea where this is being kept or how/if it is ever trimmed?

EDIT: ok I found out all about journalctl and /var/log/journal.... so that's ok

## Expected behavior

> (What you expected to happen)
no errors in the log

## Actual behavior

> (What actually happened)

## Steps to reproduce
it's there all the time
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there @dpgh947 👋 

Thanks for reporting an issue. Unfortunately, this is an issue with Grafana itself and not caused by the add-on. Please report this issue with the Grafana project.

Thanks 👍 

../Frenck
