### ISSUE TITLE
Grafana 10.2.0 broke the "&kiosk" query string flag resulting in chart heading/filters showing up

### ISSUE THREAD

**Issue by rv-kip** [hassio-addons/addon-grafana#430]
# Problem/Motivation

> I started seeing Grafana headers/filters in my iframe cards even with `&kiosk` in the query string for the chart url

## Expected behavior

> No header/filter displayed when `&kiosk` is in the url. Just the chart/graph displays.

## Actual behavior

> I am seeing headers and filters for all my iFrame Grafana charts when `&kiosk` is in the url. Downgrading to Grafana Add-On V10.1.1 fixed the issue

## Steps to reproduce

> Create an iframe card using a local Grafana link with 10.2.0 and notice the displayed heading/filter. Downgrading to Grafana Add-On V10.1.1 fixed the issue
Ex:
```
type: iframe
url: >-
  http://192.168.86.22:3000/api/hassio_ingress/.../charts?orgId=1&viewPanel=3&kiosk
```

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by PetrMa** [comment]
I have the same issue after update from Grafana v11.3.0 (d9455ff7db) to Grafana v11.2.2 (c47b921ef4)
As I think this issue is related to Grafana, not this plugins I create a bug report on Grafana Github also
https://github.com/grafana/grafana/issues/96595

**Comment by PetrMa** [comment]
adding &_dash.hideTimePicker to my URL solved my problem. thanks

**Comment by rv-kip** [comment]
I can't recall where I dug up the `&kiosk` flag. If this is a Grafana change, then I suppose this ticket can be closed.
