### ISSUE TITLE
Update 2.2.2 error 

### ISSUE THREAD

**Issue by frafaorgens** [hassio-addons/addon-grafana#44]
# Problem/Motivation
After updating to 2.2.2, this error appears. 
I can't get the information from the dashboard and is always asking for the username and password.

![grafanaerror_after222](https://user-images.githubusercontent.com/14338024/61981727-55539c00-aff2-11e9-9ec1-d266e5b7c722.jpg)

**Comment by frenck** [comment]
As per release notes: It lost its data source credentials.
Enter those.

**Comment by frafaorgens** [comment]
Sorry frenck. 
I have entered the user data and the same prompt always appears for re-entering the data.
Will it be a browser problem?

Thx

**Comment by sinclairpaul** [comment]
@frafaorgens You need to reset the password on the Datasource for Influxdb (i.e. re-enter what it is).  You also may want to clear any cookies you have for the site.

**Comment by frafaorgens** [comment]
@sinclairpaul thx!!! 
that was it!
