### ISSUE TITLE
Can't login to grafana anymore

### ISSUE THREAD

**Issue by rradar** [hassio-addons/addon-grafana#45]
# Problem/Motivation

> Can't login to grafana anymore

## Expected behavior

> Use ha credentials to login

## Actual behavior

> Error:

`lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"`

## Steps to reproduce

> Can't tell exactly. I suffered from #39 before. Now I updated all (ha & grafana) at once to the latest. Now I can't login anymore. 
>
> My config:
```
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "plugins": [],
  "env_vars": [
    {
      "name": "GF_USERS_ALLOW_SIGN_UP",
      "value": "true"
    },
    {
      "name": "GF_AUTH_ANONYMOUS",
      "value": "true"
    }
  ]
}
```

**Comment by rradar** [comment]
Just do be sure I stripped my config to the essentials as follows:

```
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "plugins": [],
  "env_vars": [ ]
}
```

Still can't login (latest grafana v2.2.2 and latest ha 0.97.0)

Error from grafana log:


```
t=2019-08-09T... lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:80 protocol=http subUrl= socket=
t=2019-08-09T... lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=192.168.X.Y time_ms=10 size=57 referer=
t=2019-08-09T... lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
t=2019-08-09T... lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=192.168.X.Y time_ms=317 size=70 referer=http://hassio:3000/login
```

the login credentials (user and password) works for home assistant

**Comment by frenck** [comment]
The grafana username/password is not linked to Home Assistant.....

**Comment by rradar** [comment]
No joke. Absolutely right @frenck. Sorry for the hassle.

I reset my grafana install due to troubles related to #39 and forgot to change the default credentials (admin/hassio) again.
