### ISSUE TITLE
embedede frame - ... will be fixed in the next release ...

### ISSUE THREAD

**Issue by svenzimmermann** [hassio-addons/addon-grafana#47]
Same problem here with embeded frame. Shoud this be fixed in the actual release? I am confused. 

Originally posted by @frenck in https://github.com/hassio-addons/addon-grafana/issues/38#issuecomment-498209865_

cu
Sven

**Comment by frenck** [comment]
That issue has been addressed.
Since you've provided 0 information, I consider this issue solved.

Feel free to open a new issue, adding in information that I can actually debug.
