### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by jeremyfoucault** [hassio-addons/addon-grafana#48]
# Problem/Motivation

When I start my graphana a message with "Unexpected error".
And no modification work.
Can you help me?

My config :
{
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "plugins": [],
  "env_vars": []
}

My log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Grafana
 The open platform for beautiful analytics and monitoring
-----------------------------------------------------------
 Add-on version: 2.2.4
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.97.2
 Supervisor version: 183
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grafana.sh: executing... 
[cont-init.d] grafana.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[05:04:19] INFO: Starting Memcached...
[05:04:20] INFO: Starting Grafana...
t=2019-08-25T05:04:21+0200 lvl=info msg="Starting Grafana" logger=server version=6.3.3 commit=84d0a71 branch=HEAD compiled=2019-08-15T11:08:12+0200
t=2019-08-25T05:04:21+0200 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2019-08-25T05:04:21+0200 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2019-08-25T05:04:21+0200 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2019-08-25T05:04:21+0200 lvl=info msg="Path Data" logger=settings path=/data
t=2019-08-25T05:04:21+0200 lvl=info msg="Path Logs" logger=settings path=/var/logs/grafana
t=2019-08-25T05:04:21+0200 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2019-08-25T05:04:21+0200 lvl=info msg="Path Provisioning" logger=settings path=/usr/share/grafana/conf/provisioning
t=2019-08-25T05:04:21+0200 lvl=info msg="App mode production" logger=settings
t=2019-08-25T05:04:21+0200 lvl=info msg="Initializing SqlStore" logger=server
t=2019-08-25T05:04:21+0200 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2019-08-25T05:04:21+0200 lvl=info msg="Starting DB migration" logger=migrator
t=2019-08-25T05:04:21+0200 lvl=info msg="Initializing HTTPServer" logger=server
t=2019-08-25T05:04:21+0200 lvl=info msg="Initializing InternalMetricsService" logger=server
t=2019-08-25T05:04:21+0200 lvl=info msg="Initializing RemoteCache" logger=server
t=2019-08-25T05:04:21+0200 lvl=info msg="Initializing QuotaService" logger=server
t=2019-08-25T05:04:21+0200 lvl=info msg="Initializing PluginManager" logger=server
t=2019-08-25T05:04:21+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2019-08-25T05:04:22+0200 lvl=info msg="Plugin dir created" logger=plugins dir=/var/lib/grafana/plugins
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing RenderingService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing AlertEngine" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing DatasourceCacheService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing HooksService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing LoginService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing SearchService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing ServerLockService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing TracingService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing UsageStatsService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing UserAuthTokenService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing CleanUpService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing NotificationService" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing provisioningServiceImpl" logger=server
t=2019-08-25T05:04:22+0200 lvl=info msg="Initializing Stream Manager"
t=2019-08-25T05:04:22+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:80 protocol=https subUrl= socket=
2019/08/25 05:04:39 http: TLS handshake error from 192.168.1.2:58419: remote error: tls: unknown certificate
2019/08/25 05:04:39 http: TLS handshake error from 192.168.1.2:58418: remote error: tls: unknown certificate
2019/08/25 05:04:40 http: TLS handshake error from 192.168.1.2:58424: remote error: tls: unknown certificate
2019/08/25 05:04:40 http: TLS handshake error from 192.168.1.2:58423: remote error: tls: unknown certificate
2019/08/25 05:04:41 http: TLS handshake error from 192.168.1.2:58430: remote error: tls: unknown certificate
2019/08/25 05:04:41 http: TLS handshake error from 192.168.1.2:58433: remote error: tls: unknown certificate
2019/08/25 05:04:41 http: TLS handshake error from 192.168.1.2:58432: remote error: tls: unknown certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x16248]
goroutine 200 [running]:
github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).ParseOs(0x2a3a7e0, 0x2945100, 0x73, 0x7315c)
	/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:284 +0xb8
github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse.func2(0x2ca6f00, 0x2a3a7e0, 0x2945100, 0x73, 0x2fba4d0)
	/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:233 +0x68
created by github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse
	/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:230 +0x13c
Signal handled: Terminated.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by przemo** [comment]
I experience similar behavior when (panic and termination) when entering the admin panel on grafana. I am unable to change the default login credentials.

**Comment by rkotulan** [comment]
Same problem as @przemo

**Comment by sinclairpaul** [comment]
Looks to be an upstream issue specific to Arm 32 bit.

Will likely need to wait for the next Grafana release.
