### ISSUE TITLE
Allow for environment variables to be specified inside the Grafana container.

### ISSUE THREAD

**Issue by erikdewildt** [hassio-addons/addon-grafana#5]
# Problem/Motivation

I'm unable to overrule some configuration settings of Grafana.

At the moment i'm using the `Grafana` addon from the https://github.com/bestlibre/hassio-addons repository. This addon allows for custom configuration settings to be specified using the `env_var` keyword. I use this to configure proxy authentication. I authenticate on a reverse proxy which then sets a header so that Grafana skips the password request. 

Unfortunately the addon in the `bestlibre` repo is an old version of Grafana, therefore i would like to use this addon.

## Expected behavior

Allowing customer configuration settings to be specified from the `hassio` addon detail page. 

## Actual behavior

When i specify the `env_var` key it's removed automatically and environment variables are not available in the container.

## Steps to reproduce

1. Set the `env_var` key in the config dict:

```
{
  "env_var": [
    {
      "name": "GF_SERVER_DOMAIN",
      "value": "home.mydomain.nl"
    },
    {
      "name": "GF_SERVER_ROOT_URL",
      "value": "%(protocol)s://%(domain)s:/_grafana"
    },
    {
      "name": "GF_AUTH_PROXY_ENABLED",
      "value": "true"
    },
    {
      "name": "GF_AUTH_PROXY_HEADER_NAME",
      "value": "X-WEBAUTH-USER"
    },
    {
      "name": "GF_AUTH_PROXY_HEADER_PROPERTY",
      "value": "username"
    },
    {
      "name": "GF_USERS_ALLOW_SIGN_UP",
      "value": "false"
    },
    {
      "name": "GF_AUTH_PROXY_AUTO_SIGN_UP",
      "value": "false"
    }
  ]
}
```
2. Save the config
3. Start the addon
4. Login to the container, check the environment variables

## Proposed changes

It would be awesome if the `env_var` key could be parsed and the environment variables would be made available inside the `grafana` container.

Thanks for all your work!

<blockquote><img src="https://avatars1.githubusercontent.com/u/621360?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/bestlibre/hassio-addons">bestlibre/hassio-addons</a></strong></div><div>Contribute to hassio-addons development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
I understand you'd like these features. Please note that this add-on is not a fork of the official Grafana docker images, so those env variables will not work.

Secondly, I'm not going to do this with env variables... ever. Hass.io provides a proper configuration mechanism, which in my opinion should be used (and not introduce a second one).

I will look into the possibilities to make these options available via the add-on configuration.

Thank you so much for the extensive ticket and pretty awesome feature request (including a proper use case) 👍

**Comment by erikdewildt** [comment]
Hi Frenck,

Thanks for the response. I understand Hassio.io has an excellent configuration mechanism. What I meant was to utilise the default Grafana feature to manipulate configuration using the the `GF_<SectionName>_<KeyName>` environment variables as documented [in the Grafana docs](http://docs.grafana.org/administration/provisioning/#using-environment-variables). This way it is not needed to render the configuration based on settings.

I've tried using the `environment` addon setting as stated in the [docs](https://developers.home-assistant.io/docs/en/hassio_addon_config.html). The docs state `A dict of environment variable to run add-on.` if I understand correctly these variables are ment to be passed to the container (docker run -e ... )? Unfortunately for some reason my settings are not saved and reverted automatically, not sure what I'm doing wrong.

It to me that seems that if I'm able to save settings in the `environment` key of the addon my feature would work.

I would be more then happy to share a small NGINX config snippet which arranges `automatically` login in Grafana for my local subnet.

Thanks again,
Regards,

Erik

**Comment by frenck** [comment]
This Hass.io environment setting you are referring to is statically configured in the add-on and cannot be modified or set by the user.

**Comment by mrfawy** [comment]
First of all , thanks Frenck for the awesome add on .
I'd like to add my voice to @erikdewildt request. My use case is that I need to send email Alerts from Grafana and to do that , I need to change smtp settings. (in docker via env_var) . 

If environment settings are static , how can I do that ?

Best Regards,
