### ISSUE TITLE
Update from 2.3.0 to 3.0.0 -> no login possible

### ISSUE THREAD

**Issue by Alex9779** [hassio-addons/addon-grafana#51]
# Problem/Motivation
Updated from 2.3.0 to 3.0.0 and was not able to login anymore to the instance.

## Expected behavior
Being able to login...

## Actual behavior
If I entered wrong user or password the login screen told me so but using the right credentials I got a white page with just the text `{message: authorization failed}` or something, can‘t remember.
Unfortunately I didn‘t make a snapshot, cannot go back so I deleted the addon an reinstalled.

## Steps to reproduce
no idea, maybe upgrade to 3.0.0 from an 2.3.0 instance with setup security

**Comment by Alex9779** [comment]
Ok a little more information, the message is `{"message":"Unauthorized"}`.
I was able to get to there again with a new installation of 3.0.0.
I logged into as admin and changed the organization name.
The log has error messages:
```
t=2019-11-01T08:49:35+0100 lvl=eror msg="Anonymous access organization error: 'Main Org.': Organization not found"
```
I can‘t login anymore.

**Comment by Alex9779** [comment]
Hmmmm now I think I know I may have fixed that by using the config with env variables to set the anonymous organization used, well that‘s live.
But maybe there should be a note in the install guide, if you changed your organization you will have to set additional vars to make it working, if that is the reason...

**Comment by quazzie** [comment]
Same problem, had changed my organisation in previous version.
Fixed it by updating the name column in the org table in /usr/share/hassio/addons/xxx_grafana/grafana.db to 'Main Org.'

```
{message: authorization failed}
"Anonymous access organization error: 'Main Org.': Organization not found"
```

**Comment by frenck** [comment]
This happens when the organization's name was changed from the defaults.

You can configure the correct organization name using the add-on `env_vars`, for example:

```
{
  "plugins": [],
  "env_vars": [
    {
      "name": "GF_AUTH_ANONYMOUS_ORG_NAME",
      "value": "Frenck.dev"
    }
  ]
}
```

**Comment by wneessen** [comment]
I have the same issue. Problem is, I am not aware I changed the organization (which does not mean, that I haven't done it). Is there a way to find out what the correct setting for the env_var is?

**Comment by frenck** [comment]
@wneessen Restore a snapshot and check out using the previous version?

**Comment by quazzie** [comment]
@wneessen 
```
sqlite3 /usr/share/hassio/addons/data/a0d7b954_grafana/grafana.db
select name from org;
```

**Comment by wneessen** [comment]
That did the job, thanks @quazzie!
