### ISSUE TITLE
Embedded iframes broken 

### ISSUE THREAD

**Issue by kloknibor** [hassio-addons/addon-grafana#52]
# Problem/Motivation

> (Why the issue was filed)
After the update to v3.0.0 all embedded iframes stopped working. I assume this is because the ingress support, but I just want to share graphs externally, so ingress doesn’t solve this issue. 

## Expected behavior

> (What you expected to happen)
I expected my embedded iframes to work as they always did. I expected my graph loaded in the iframe and displayed correctly
## Actual behavior

> (What actually happened)
The actual behaviour is that the resource where normally the graph was available is now unavailable
## Steps to reproduce

> (How can someone else make/see it happen)
Create within grafana an embedded link and try to access it.
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Direct access to the add-on has been removed in favor of ingress support in v3.0.0.

This will break some use cases and add a bunch of new ones.

This cannot be fixed and will not change.
