### ISSUE TITLE
Port 3000 no longer exposed

### ISSUE THREAD

**Issue by VuokkoVuorinnen** [hassio-addons/addon-grafana#54]
# Problem/Motivation

I used to use the nginx proxy manager to expose the grafana instance on grafana.domain.com. It was setup to reverse proxy http://hassio.local:3000 but since the update to 3.0 this doesn't work anymore. nmap of my hassio instance shows that port 3000 is closed now.

## Expected behavior

Port 3000 to be open, and serving the grafana web interface

## Actual behavior

Port 3000 is closed, grafana webinterface only accessible from within home assistant

## Steps to reproduce

Update to latest version of grafana addon

## Proposed changes

Add an option to enable exposing the http port. Much like the hassio influxdb addon:

```
Container | Host | Description
-- | -- | --
80/tcp |   | Web interface (Not required for Hass.io Ingress)
8086/tcp |   | InfluxDB server
````

**Comment by frenck** [comment]
Please read the release note, since it was announced it would be closed in there.

**Comment by VuokkoVuorinnen** [comment]
And I would like an option to open it myself if I want to... Not a big fan of the home assistant ingress stuff...

**Comment by frenck** [comment]
Grafana cannot support both at the same time. Ingress is requested a lot and fits the paradigm of Hass.io better.

Feel free to maintain a fork of the add-on or install Grafana manually yourself.

**Comment by kloknibor** [comment]
Anyway to downgrade to a version we are happy with? Or do we need to make a fork for that...?

**Comment by kloknibor** [comment]
(also I would also be made happy if this could be made reality, but if it's not technically possible it is what it is...)

**Comment by frenck** [comment]
You can restore a snapshot of the add-on before upgrading.
Hass.io does not offer version selection for add-ons.

**Comment by kloknibor** [comment]
That would destroy a lot of data. But I just checked the commits out, most is quite easily to maintain. I created a fork and will try to maintain this fork :-)! If more people want this, add : https://github.com/kloknibor/addon-grafana probably the quickest solution! 

<blockquote><img src="https://avatars0.githubusercontent.com/u/10560390?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/kloknibor/addon-grafana">kloknibor/addon-grafana</a></strong></div><div>Grafana - Community Hass.io Add-on for Home Assistant - kloknibor/addon-grafana</div></blockquote>

**Comment by didi767** [comment]
> That would destroy a lot of data. But I just checked the commits out, most is quite easily to maintain. I created a fork and will try to maintain this fork :-)! If more people want this, add : https://github.com/kloknibor/addon-grafana probably the quickest solution!
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/10560390?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[kloknibor/addon-grafana](https://github.com/kloknibor/addon-grafana)**Grafana - Community Hass.io Add-on for Home Assistant - kloknibor/addon-grafana

I have the same issue, can't seem to use curl now because of this ingress mode, how can i downgrade to a previous version of grafana? (I'm pretty new to HA)
I'm using VM to host my hassio.
Thanks,

**Comment by kloknibor** [comment]
Either you just restore the grafana add-on from your hassio snapshots or you add my repo kloknibor/addon-grafana and install grafana from there ;-)!

**Comment by didi767** [comment]
> Either you just restore the grafana add-on from your hassio snapshots or you add my repo kloknibor/addon-grafana and install grafana from there ;-)!

I'm sorry for my ignorance, but how do I add your repo? I need a URL right?
Thanks for the quick reponse btw :)

**Comment by didi767** [comment]
Found it! sorry, It was pretty dumb of me lol
Thanks for everything @kloknibor ! hopefully this will solve my issue.
