### ISSUE TITLE
Lovelace iframe or curl access to Grafana doesn't work reliably

### ISSUE THREAD

**Issue by rccoleman** [hassio-addons/addon-grafana#56]
# Problem/Motivation

I'm breaking out one of the issues discussed in [#55](https://github.com/hassio-addons/addon-grafana/issues/55) and [here](https://community.home-assistant.io/t/community-hass-io-add-on-grafana/54674/167) so that it doesn't get buried.

I would like to display a Grafana graph in Lovelace either by grabbing a rendered image periodically with curl or embedding the Grafana link in a Lovelace iframe.  I can open the Grafana "share" link in a Lovelace iframe or a separate tab in the browser where I've opened Grafana through the sidebar, but attempting to open that same URL anywhere else, another browser or via `curl`, results in a `401: Unauthorized` error in the browser and `WARNING (MainThread) [hassio.api.ingress] No valid ingress session None` in the system log.

## Expected behavior

I should be able to view or download a rendered graph image from anywhere where I can access my HA instance.

## Actual behavior

I get a `401: Unauthorized` reponse and `WARNING (MainThread) [hassio.api.ingress] No valid ingress session None` in the system log.

## Steps to reproduce

I've created an API key in Grafana and added it in an authentication header like this:

curl -H "Authorization: Bearer <api_key>" "http://192.168.1.159:8123/api/nxFDlLCmLm3kWapLd8bHEPR4Y_s6_2Z3LugpaYyTqkQ/render/d-solo/bWkFVQ0Wz/energy-usage?orgId=1&from=1573337107888&to=1573340707888&panelId=2&width=1000&height=500&tz=America%2FLos_Angeles"

I've also tried using the same command with my Home Assistant LLAT that works with other HA APIs, and with basic auth in the URL using a user/password that I created in Grafana.

If I open the URL from a browser where I've already opened the Grafana web UI from the addon page or sidebar, it works fine.  It fails everywhere else.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by dsasov88** [comment]
same for me

**Comment by tibzz42** [comment]
Same here :(

**Comment by didi767** [comment]
SAME HERE :(
Tried to solve this issue for 6 hours yesterday, always the same result.
the png file is empty and trying to access the url outside my local network gives 401 authorization error.

**Comment by lejban** [comment]
I have the same problem: 401: Unauthorized

**Comment by f00dagi** [comment]
Same problem for me.

**Comment by SweVictor** [comment]
Same here (works after accessing the full Grafana UI). I actually would prefer improvements suggested in various Grafana forums such as http://api_key:[key]@host:port/...., but anonymous access (read-only) is absolutely good enough and something that would make the Grafana add-on really helpful. Without access for other people in the household I suppose I would have to go back to "simpler" visualization tools. Seems I can't really solve this on my own.

/Victor

**Comment by pdeelen** [comment]
Same for me :(

**Comment by sinclairpaul** [comment]
Direct access is now available again in the latest release, closing.

**Comment by rccoleman** [comment]
While it's great that direct access has been enabled (thanks!), it doesn't directly address this issue.  Other than via direct access, which isn't desirable if remote access is handled via Nabu Casa, I'm still unable to "tunnel" Grafana requests through Ingress in order to add a graph to lovelace.  Somehow I think we need to be able to use an iframe URL that gets both through Nabu Casa Ingress and Grafana.

**Comment by sinclairpaul** [comment]
An Iframe is client driven though, what you are requesting is some form of generic authentication proxy for ingress.   This would be outside the scope of the addon itself, and would need to be raised at the Hassio repo (if it would be possible).

**Comment by rccoleman** [comment]
I assumed that a LLAT would serve that purpose, as it does for normal API access, but I agree that that's the first step.

**Comment by rdariolemes** [comment]
@sinclairpaul Still doesn't work. U have to login into graffana first to be able to see the links on the iFrame. Also curl still gets Unauthorized.
