### ISSUE TITLE
Duplicate Sidebar Icon with old icon broken

### ISSUE THREAD

**Issue by tscs37** [hassio-addons/addon-grafana#57]
# Problem/Motivation

When upgrading to the latest version with the sidebar icon enabled via "Show in Sidebar" the icon is duplicated; one of the icons leads to a 502 page, the other leads to grafana proper.

## Expected behavior

Upgrading to the latest version should update the sidebar icon to the new ingress

## Actual behavior

The sidebar icon shows for both the old and new ingress, the old icon does not work at all and leads to an error page.

## Steps to reproduce

1. Setup Hass.io with the old version (<3.0.0)
2. Activate Sidebar Icon
3. Upgrade to latest version (3.0.0)
4. The old Sidebar Icon is now broken
5. De- and Reactivate Sidebar Icon

## Proposed changes

The Addon should clear the old icon before or after upgrading, this was likely introduced when the addon changed to the new ingress method.

**Comment by frenck** [comment]
Correct, that is why instructions for this where written in the release notes: <https://github.com/hassio-addons/addon-grafana/releases/tag/v3.0.0>
