### ISSUE TITLE
You need to sign in to star dashboards

### ISSUE THREAD

**Issue by pdeelen** [hassio-addons/addon-grafana#61]
# Problem/Motivation

> I want to set a home dashboard

## Expected behavior

> You need to star a dashboard to select it, that is not possible

## Actual behavior

> When i click on the star right after the dashboard at the home page i receive an error "You need to sign in to star dashboards"

**Comment by frenck** [comment]
Yes... you need to sign in into Grafana in order to star dashboards.
That is a Grafana limitation, not an add-on limitation.

Not much I can do about this.
