### ISSUE TITLE
Invalid memory address or nil pointer dereference stack="/usr/local/go/src/runtime/panic.go:199 

### ISSUE THREAD

**Issue by d4icon** [hassio-addons/addon-grafana#63]
# Problem/Motivation

> i cant login InfluxDB 

## Expected behavior

> login correct

## Actual behavior

>  error with:
[05/Jan/2020:17:23:55 +0100] 500 192.168.1.38, 172.30.32.1(172.30.32.2) GET /api/datasources/proxy/1/query?q=SHOW+RETENTION+POLICIES+on+%22%22&epoch=ms HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0)
[05/Jan/2020:17:24:04 +0100] 200 192.168.1.38, 172.30.32.1(172.30.32.2) PUT /api/datasources/1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0)
[05/Jan/2020:17:24:04 +0100] 200 192.168.1.38, 172.30.32.1(172.30.32.2) GET /api/frontend/settings HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0)
[05/Jan/2020:17:24:04 +0100] 200 192.168.1.38, 172.30.32.1(172.30.32.2) GET /api/datasources/1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0)
t=2020-01-05T17:24:04+0100 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:199 (0x4502db)\n/usr/local/go/src/runtime/signal_unix.go:394 (0x450118)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:216 (0xf9470d)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:68 (0xf93a12)\n/go/src/github.com/grafana/grafana/pkg/api/dataproxy.go:35 (0x12fefc8)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5efd5)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xc5efc8)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5e7cc)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xc5e7b7)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5e6df)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:147 (0xc5e6cd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x82b820)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x82a6e9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x82a478)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xc5bf2b)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xc5bf16)\n/usr/local/go/src/reflect/value.go:460 (0x49b5f5)\n/usr/local/go/src/reflect/value.go:321 (0x49adb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x82a9d9)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x82a389)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82b978)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x83cad6)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x8373a5)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x83086a)\n/usr/local/go/src/net/http/server.go:2802 (0x70a533)\n/usr/local/go/src/net/http/server.go:1890 (0x705ed4)\n/usr/local/go/src/runtime/asm_amd64.s:1357 (0x46a9f0)\n"

## Steps to reproduce
![imagen](https://user-images.githubusercontent.com/5176086/71782972-a2478f80-2fe0-11ea-829f-adfc1a2e98d8.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Can you look at the read me for Grafana which explains how to configure the connection?  Although the application throwing the exception isn't particularly nice (and would be an upstream issue), it would appear that you missed specifying http/https on the URL.

**Comment by omarhass** [comment]
I am faced with this invalid memory address issue lately and the http/https is correctly entered in the field. Any idea on what other reasons would trigger it?
