### ISSUE TITLE
Grafana not starting

### ISSUE THREAD

**Issue by fernmac2** [hassio-addons/addon-grafana#65]
Grafana is simply not starting. I tried SSL: false but I do not even have a log, and nothing also on HA log. I do not know where to begin.
Thanks for any help.
![Screenshot 2020-02-26 at 11 06 03](https://user-images.githubusercontent.com/44324624/75339322-2d7a2e80-5888-11ea-8cd4-e9b135ee73ad.png)

**Comment by frenck** [comment]
Please check the output of the Supervisor log.

Supervisor panel -> System tab -> Logs

**Comment by frenck** [comment]
No response, closing issue. Feel free to join or Discord server if you need further assistance.

Thanks! 👍
