### ISSUE TITLE
Uninstall not working

### ISSUE THREAD

**Issue by DaveRuijter** [hassio-addons/addon-grafana#66]
Hi, I'm having issues with uninstalling the Grafana addon.
When I click 'uninstall' it does not seem to actually uninstall it.
What can I do to manually uninstall it?
Thanks in advance!

**Comment by sinclairpaul** [comment]
Can you share the supervisor log?, you may also want to run `ha supervisor repair` from the SSH/Web addon

**Comment by frenck** [comment]
This is really out of scope for us.
We can only manage the runtime of an add-on. Anything outside of that is managed and the responsibility of Home Assistant. Please raise an issue with the Home Assistant project.

Thanks 👍
