### ISSUE TITLE
Install custom plugin 

### ISSUE THREAD

**Issue by giuliovale** [hassio-addons/addon-grafana#68]
Ideas on how to install custom plugins?
I need to install 
https://github.com/CorpGlory/grafana-multibar-graph-panel

Thanks

<blockquote><img src="https://avatars2.githubusercontent.com/u/20858176?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CorpGlory/grafana-multibar-graph-panel">CorpGlory/grafana-multibar-graph-panel</a></strong></div><div>A plugin implementing https://github.com/grafana/grafana/issues/870 - CorpGlory/grafana-multibar-graph-panel</div></blockquote>

**Comment by sinclairpaul** [comment]
Sorry that isn't supported in the addon.

**Comment by disrupted** [comment]
just came to ask the same, was hoping to use the same plugin for a nifty Health dashboard
