### ISSUE TITLE
Upgrade grafana to 7.0.1

### ISSUE THREAD

**Issue by kamontat** [hassio-addons/addon-grafana#69]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by kamontat** [comment]
Why you didn't use grafana docker directly ? 

> https://grafana.com/docs/grafana/latest/installation/docker/

**Comment by kamontat** [comment]
upgrade step

> https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v7-0

**Comment by frenck** [comment]
@kamontat Because:
A) Add-ons do more things than just Docker, which our base images provide.
B) We don't ship on unstable alpha base images, as Grafana did.

Upgrade is pending.

**Comment by frenck** [comment]
Done!
