### ISSUE TITLE
Grafana image rendering no longer working

### ISSUE THREAD

**Issue by MrAlfabet** [hassio-addons/addon-grafana#70]
Since the update there is no longer an image renderer installed by default in the grafana docker image, nor is the image renderer plugin compatible with the current Grafana Docker image without installing further system-level dependencies. See https://grafana.com/grafana/plugins/grafana-image-renderer

This interferes with the way I bring grafana graphs into my lovelace dashboard (unless I've missed a better way without curl'ing the image url).

Perhaps this is a solution? https://grafana.com/docs/grafana/latest/installation/docker/#build-with-grafana-image-renderer-plugin-pre-installed

<blockquote><img src="https://grafana.com/api/plugins/grafana-image-renderer/versions/2.0.0/logos/large" width="48" align="right"><div>Grafana Labs</div><div><strong><a href="https://grafana.com/grafana/plugins/grafana-image-renderer">Grafana Image Renderer plugin for Grafana</a></strong></div><div>Grafana Backend Image Renderer that uses headless chrome to capture images.</div></blockquote>
<blockquote></blockquote>

**Comment by IsaTTeN** [comment]
I have the same problem, I use the rendered images to send them to Twitter, but now I get this message: Rendering failed.

I have installed the plugin using this line in the configuration:
`plugins:
  - grafana-image-renderer`

**Comment by frenck** [comment]
Release is inbound:

![image](https://user-images.githubusercontent.com/195327/83402909-f461d500-a407-11ea-835e-3e7ef4d19a71.png)
