### ISSUE TITLE
Grafana gives an error when using the (beta) transform on data

### ISSUE THREAD

**Issue by MrAlfabet** [hassio-addons/addon-grafana#72]
# Problem/Motivation

> Grafana gives an error when using the (beta) transform on data

## Actual behavior

    An unexpected error happened
    Details
    TypeError: Cannot read property 'data' of null

    in t
    in div
    in Ma
    in div
    in an
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

## Steps to reproduce

> Install grafana addon, select some data, click transform, select Add field from calculation.

## Proposed changes

> Not sure if this is an add-on thing, but I thought I'd mention it.

**Comment by bennealon** [comment]
Hi, i'm seeing this aswell - i found this issue on grafana's github https://github.com/grafana/grafana/issues/25194, apparently its fixed in 7.0.3. I noticed 116b16d1d5f3c216b2faac7680f28436db9b3d93 references this version, but it doesnt look released yet - any idea when the next release will be @frenck ?

**Comment by mafelipe16** [comment]
Im checking the Grafana Add-on and says that is upgraded to Grafana 7.0.3 version, this version should fix the Transformation issue but....inside Hassio the Grafana version keeps saying 7.0.2 Is this not yet promoted?

**Comment by bennealon** [comment]
> Im checking the Grafana Add-on and says that is upgraded to Grafana 7.0.3 version, this version should fix the Transformation issue but....inside Hassio the Grafana version keeps saying 7.0.2 Is this not yet promoted?

The latest Grafana won;t autoamtically make its way to homeassistant, it looks like @frenck has already updated the version and checked this in - it just needs a release, eagerly awaiting this myself too 👍

**Comment by frenck** [comment]
Fixed in latest release.
