### ISSUE TITLE
SMTP Settings?

### ISSUE THREAD

**Issue by greenwoodsteven** [hassio-addons/addon-grafana#73]
How can one set the Email server settings (SMTP) in grafana for hassio?

More Infos here:
https://grafana.com/docs/grafana/latest/installation/configuration/#smtp

thanks in advance

**Comment by greenwoodsteven** [comment]
How can one set the Email server settings (SMTP) in grafana for hassio?

More Infos here:
https://grafana.com/docs/grafana/latest/installation/configuration/#smtp

thanks in advance

**Comment by sinclairpaul** [comment]
Set the Environment Variables:

https://github.com/hassio-addons/addon-grafana/blob/master/grafana/DOCS.md#option-env_vars

**Comment by greenwoodsteven** [comment]
For those interested here is my working hassio grafana smtp config:
`plugins: []
env_vars:
  - name: GF_SMTP_ENABLED
    value: 'true'
  - name: GF_SMTP_HOST
    value: 'smtp.googlemail.com:587'
  - name: GF_SMTP_USER
    value: myemail@googlemail.com
  - name: GF_SMTP_PASSWORD
    value: xxxx
  - name: GF_SMTP_SKIP_VERIFY
    value: 'true'
  - name: GF_SMTP_FROM_ADDRESS
    value: myemail@googlemail.com
  - name: GF_SMTP_FROM_NAME
    value: GRAFANA
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem`

Note that this is saved in hassio grafana's config and NOT hassio's config.

Note that the client side validation only allowed JSON valid entries e.g.

`
[{
        name: "GF_SMTP_ENABLED",
        value: "true"
    },

    {
        name: "GF_SMTP_HOST",
        value: "smtp.googlemail.com:587"
    },

    {
        name: "GF_SMTP_USER",
        value: "myemail@GOOGLEMAIL.COM"
    },

    {
        name: "GF_SMTP_PASSWORD",
        value: "xxxx"
    },

    {
        name: "GF_SMTP_SKIP_VERIFY",
        value: "true"
    },

    {
        name: "GF_SMTP_FROM_ADDRESS",
        value: "myemail@GOOGLEMAIL.COM"
    },

    {
        name: "GF_SMTP_FROM_NAME",
        value: "GRAFANA"
    },
]
`

As a side note, grafana's email alert supports image attachments.
In order for this to work the grafana-image-renderer (https://grafana.com/grafana/plugins/grafana-image-renderer/installation) plugin needs to be installed (also over the hassio grafana config). Unfortunately the grafana logs gave a "not supported" message after the installation of this plugin. Other plugins worked.
