### ISSUE TITLE
Ingress and alert URLs

### ISSUE THREAD

**Issue by alexiri** [hassio-addons/addon-grafana#74]
Grafana email alerts include links to view the alert page and the rule, but those links are broken because they use the internal "http://localhost:3000" URL.

I've tried setting GF_SERVER_ROOT_URL to various things (`https://homeassistant.example.com/`, `https://homeassistant.example.com/%%ingress_entry%%`, `https://homeassistant.example.com/a0d7b954_grafana`, etc), with and without GF_SERVER_SERVE_FROM_SUB_PATH, and also setting GF_SERVER_DOMAIN, GF_SERVER_PROTOCOL and GF_SERVER_HTTP_PORT, but all my attempts ended up in a non-working Grafana instance.

What do I need to set up so the URLs in the alerts actually redirect back to my Grafana instance through Ingress?

<blockquote><div><strong><a href="http://localhost:3000/">probot-addons-assistant | built with Probot</a></strong></div></blockquote>

**Comment by sinclairpaul** [comment]
I doubt anything can be done about this in the addon, as per the docs the URL is based on the domain config https://grafana.com/docs/grafana/latest/alerting/notifications/#configure-the-link-back-to-grafana-from-alert-notifications

You cannot customise this and it needs to be set to localhost as access is provided though a reverse proxy (nginx).

**Comment by alexiri** [comment]
Why wouldn't this be possible even with a reverse proxy? It's certainly possible for other Grafana installations.

Or do you mean that there are two proxies, HA's Ingress and another one in this addon?

**Comment by alexiri** [comment]
This issue has still not been resolved.

**Comment by spali** [comment]
I'm also still interested for a solution. But I also think we should keep an eye on https://github.com/home-assistant/frontend/issues/6235

**Comment by frenck** [comment]
The problem is, this cannot be solved from the add-on end. Thus keeping this issue alive on this end, has no use.
