### ISSUE TITLE
Flux

### ISSUE THREAD

**Issue by blair287** [hassio-addons/addon-grafana#77]
# Problem/Motivation

> please provide info how how to use grafana with flux enabled 

## Expected behaviour

> documentation to be added for using flux
## Actual behaviour

> no documentation

## Steps to reproduce

> No idea how to set up

## Proposed changes

> I have enabled the flux plugin in grafana but no idea what the setting should be to link the new data source for influxdb, I think this info is need as without flux you cannot query by month which is a massive hole in the capabilities of a DB if you ask me.

I am happy to write up the documentation with pictures once i know how to do it but currently dont know any of the settings to connect.

![flux](https://user-images.githubusercontent.com/44187409/93460220-ce8b0e00-f8da-11ea-9bda-da56938de63d.JPG)

**Comment by dpjrodrigues** [comment]
I don't think you will be able to use grafana flux connection with the existent InfluxDB HA addon.
the version used in the influxDB addon is 1.8.3 (which already have flux... and you can test it in the UI) but there was a major change with the influxDB APIs from 2.x onwards and that Grafana connection is prepared for that new version only.

In my view this is not a Grafana issue... it can be solved once InfluxDB addon is updated to 2.x or if you install 2.x separately.
