### ISSUE TITLE
Error with the 2020.10.0 supervisor

### ISSUE THREAD

**Issue by d0ugal** [hassio-addons/addon-grafana#80]
# Problem/Motivation

After upgrading the supervisor I get the following error when the adding attempts to start.

```
20-10-29 07:40:45 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons.json: [Errno 1] Operation not permitted: '/data/addons.json'
20-10-29 07:40:45 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/a0d7b954_grafana/options.json: [Errno 1] Operation not permitted: '/data/addons/data/a0d7b954_grafana/options.json'
20-10-29 07:40:45 ERROR (MainThread) [supervisor.addons.addon] Add-on a0d7b954_grafana can't write options
```

## Expected behavior

Normal start as with previous supervisors

## Actual behavior

Above error

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please report errors with the supervisor with the Home Assistant project. From an add-on perspective, there is nothing I can do.
