### ISSUE TITLE
image: hassioaddons/grafana-armv7:5.3.3

### ISSUE THREAD

**Issue by tof92130** [hassio-addons/addon-grafana#81]
# Problem

I am working with a Raspberry pi4

After upgrading to hassio 0.117.1, I upgraded influxDB and grafana 
When I start grafana, it returns me the message :

404 Client Error: Not Found ("No such image: hassioaddons/grafana-armv7:5.3.3")

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/97788737-66a73300-1bbb-11eb-8511-49c4ca5557c3.png)


It exists.

Furthermore upgrading of Home Assistant 0.117.1 is never related to add-ons (oh and hassio doesn't exist anymore for quite some time now).
