### ISSUE TITLE
Repostitory structure for master is not compliant

### ISSUE THREAD

**Issue by Zuendelmeister** [hassio-addons/addon-grafana#85]
# Problem/Motivation

> I cannot install the addon because I cannot add the repo to HACS

## Expected behavior

> I should find it in the HACS Addon Overview

## Actual behavior

> Repostitory structure for master is not compliant

## Steps to reproduce

> In Home Assistanc: Click HACS => The three dots top right => Custom Repositories => Add the repo URL =>Choose Category => Click Add

**Comment by sinclairpaul** [comment]
https://hacs.xyz/docs/faq/addons

**Comment by sinclairpaul** [comment]
Also https://github.com/hassio-addons/addon-grafana/blob/master/grafana/DOCS.md#installation
