### ISSUE TITLE
Grafana add-on updated to 6.0.0 - fail to start

### ISSUE THREAD

**Issue by MDSDM** [hassio-addons/addon-grafana#92]
# Problem/Motivation

Grafana is not starting/accessable

## Expected behavior

Once update is done, start Grafana

## Actual behavior

Seems stuck in the updating process

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

## System

supervisor-2021.01.5
core-2021.1.4
Home Assistant OS 5.10

**Comment by MDSDM** [comment]
Removed the instance completely and reinstalled. Seems to work then.

**Comment by frenck** [comment]
There is not information in this issue. Please share logs. Without it, there is nothing I can do.

**Comment by MDSDM** [comment]
Which one of them?

**Comment by frenck** [comment]
Supervisor and add-on logs (or any logs that shows an related error)

**Comment by MDSDM** [comment]
I'm sorry about the Grafana log, I think it went down the drain when I remove the old version. So I'm gonna get a hard time to reproduce the error.

21-01-22 18:07:52 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_a0d7b954_grafana application
21-01-22 18:07:55 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_grafana application
21-01-22 18:07:59 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_grafana!
21-01-22 18:08:00 ERROR (MainThread) [supervisor.utils] Can't execute update while a task is in progress
21-01-22 18:08:00 ERROR (MainThread) [supervisor.utils] Can't execute cleanup while a task is in progress
21-01-22 18:08:00 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_grafana' successfully updated
21-01-22 18:08:00 ERROR (MainThread) [supervisor.utils] Can't execute run while a task is in progress
21-01-22 18:08:00 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/grafana/amd64 with version 5.3.6
21-01-22 18:08:00 ERROR (MainThread) [supervisor.api.security] Invalid token for access /addons/self/info
21-01-22 18:08:01 ERROR (MainThread) [supervisor.api.security] Invalid token for access /host/info
21-01-22 18:08:01 ERROR (MainThread) [supervisor.api.security] Invalid token for access /info
21-01-22 18:08:06 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_grafana application
21-01-22 18:08:06 ERROR (SyncWorker_0) [supervisor.docker] Image ghcr.io/hassio-addons/grafana/amd64 not exists for addon_a0d7b954_grafana

**Comment by frenck** [comment]
I have really no answer for you. It looks like something that is outside of the add-on. For example, those token messages, that is not something the add-on has control over.

**Comment by MDSDM** [comment]
Thank you for coming back to this. 

I think it went bonkers when the InfluxDB 4.0.0 was done. I installed 4.0.1 and now Grafana reinstall works again. 

The issue might not be resolved, but it can't be reproduced either. So I suggest the issue gets closed.

**Comment by frenck** [comment]
Alrigt, lets close it for now. Feel free to notify me again if it happens again 👍
