### ISSUE TITLE
Grafana 7.4

### ISSUE THREAD

**Issue by ViperRNMC** [hassio-addons/addon-grafana#96]
# Problem/Motivation
Is it possible to update to Grafana 7.4, new in this version is the option to rename the alias.
https://github.com/grafana/grafana/pull/29281

## Expected behavior
new features

**Comment by frenck** [comment]
Grafana 7.4 is not yet available as a general release.

**Comment by ViperRNMC** [comment]
7.4 is out now

**Comment by frenck** [comment]
@ViperRNMC We know... no need to comment for that.
